{{- if and .Values.ascend.apiKey (not .Values.ascend.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ascend-authz.fullname" . }}-secret
  labels:
    {{- include "ascend-authz.labels" . | nindent 4 }}
type: Opaque
stringData:
  api_key: {{ .Values.ascend.apiKey | quote }}
{{- end }}
