# SEC-081: Unified Authentication Module
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# This module implements the Unified Authentication architecture per
# ascend-unified-authentication-module.md specification.
#
# Components:
# - TokenService: RS256-only JWT creation and verification
# - PasswordService: Pepper + Argon2id password hashing
# - RevocationService: Token blacklist with Redis/in-memory backend
# - TenantContext: Immutable context for Layer 1 tenant establishment
#
# Compliance: SOC 2 CC6.1, NIST SP 800-63B, OWASP ASVS 2.4.4

from .constants import (
    ISSUER,
    AUDIENCES,
    ALGORITHM,
    ACCESS_TOKEN_EXPIRE_MINUTES,
    REFRESH_TOKEN_EXPIRE_DAYS,
)
from .exceptions import (
    AuthenticationError,
    TokenExpiredError,
    TokenRevokedError,
    InvalidAlgorithmError,
    InvalidSignatureError,
    InvalidClaimsError,
    PasswordHashingError,
    PepperNotConfiguredError,
)
from .tenant_context import TenantContext

__all__ = [
    # Constants
    "ISSUER",
    "AUDIENCES",
    "ALGORITHM",
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "REFRESH_TOKEN_EXPIRE_DAYS",
    # Exceptions
    "AuthenticationError",
    "TokenExpiredError",
    "TokenRevokedError",
    "InvalidAlgorithmError",
    "InvalidSignatureError",
    "InvalidClaimsError",
    "PasswordHashingError",
    "PepperNotConfiguredError",
    # Context
    "TenantContext",
]
