# SEC-081: Unified Authentication Constants
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# Compliance: SOC 2 CC6.1, NIST SP 800-131A
"""
Unified Authentication Constants for SEC-081.

These constants define the standard configuration for all authentication
operations across the Ascend platform. Modifying these values requires
security review and compliance assessment.
"""

import os
from typing import List

# =============================================================================
# JWT CONFIGURATION (RS256 ONLY)
# =============================================================================

# Issuer - identifies tokens issued by this platform
# SEC-081 Phase 4: Must match production URL for token validation
# Future migration to ascend.app will require grace period (like HS256→RS256)
ISSUER: str = os.getenv("JWT_ISSUER", "https://pilot.owkai.app")

# Audiences - valid recipients of platform tokens
# SEC-081 Phase 4: Updated to match current production domain
AUDIENCES: List[str] = [
    "pilot.owkai.app",
    "owkai-platform",
    "owkai-api",
]

# Algorithm - RS256 ONLY (asymmetric)
# HS256 is explicitly blocked per SEC-081 requirements
ALGORITHM: str = "RS256"

# Blocked algorithms - these will be rejected
# Includes "none" attack (CVE-2015-9235) and HS* algorithms
BLOCKED_ALGORITHMS: List[str] = [
    "none",
    "None",
    "NONE",
    "",
    "HS256",  # Blocked for multi-tenant security
    "HS384",
    "HS512",
]

# Token expiration
ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "60"))
REFRESH_TOKEN_EXPIRE_DAYS: int = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", "30"))

# =============================================================================
# ARGON2ID CONFIGURATION (OWASP 2024)
# =============================================================================

# Memory cost in KiB (64 MB = 65536 KiB)
ARGON2_MEMORY_COST: int = int(os.getenv("ARGON2_MEMORY_COST", "65536"))

# Time cost (iterations)
ARGON2_TIME_COST: int = int(os.getenv("ARGON2_TIME_COST", "3"))

# Parallelism (threads)
ARGON2_PARALLELISM: int = int(os.getenv("ARGON2_PARALLELISM", "4"))

# Hash length in bytes (256-bit output)
ARGON2_HASH_LENGTH: int = 32

# Salt length in bytes (128-bit salt)
ARGON2_SALT_LENGTH: int = 16

# =============================================================================
# PASSWORD PEPPER CONFIGURATION
# =============================================================================

# AWS Secrets Manager secret name for password pepper
PEPPER_SECRET_NAME: str = os.getenv(
    "ASCEND_PEPPER_SECRET_NAME",
    "owkai-pilot/sec081/ASCEND_AUTH_PASSWORD_PEPPER"
)

# Environment variable fallback for pepper
PEPPER_ENV_VAR: str = "ASCEND_AUTH_PASSWORD_PEPPER"

# =============================================================================
# TOKEN CLAIMS CONFIGURATION
# =============================================================================

# Required claims that must be present in all tokens
REQUIRED_CLAIMS: List[str] = [
    "sub",      # Subject (user UUID)
    "iss",      # Issuer
    "aud",      # Audience
    "exp",      # Expiration
    "iat",      # Issued at
    "jti",      # JWT ID (for revocation)
    "org_id",   # Organization UUID (Layer 1 tenant context)
]

# Optional claims
OPTIONAL_CLAIMS: List[str] = [
    "nbf",          # Not before
    "role",         # User role
    "tenant_id",    # Human-readable tenant ID
    "permissions",  # Permission set
    "session_id",   # Session identifier
]

# =============================================================================
# REVOCATION CONFIGURATION
# =============================================================================

# Redis key prefix for revoked tokens
REVOCATION_KEY_PREFIX: str = "ascend:revoked:"

# Redis TTL padding (additional seconds beyond token expiry)
REVOCATION_TTL_PADDING_SECONDS: int = 300  # 5 minutes

# In-memory cache max size (development only)
REVOCATION_CACHE_MAX_SIZE: int = 10000

# =============================================================================
# LEGACY COMPATIBILITY
# =============================================================================

# Grace period for accepting legacy HS256 tokens (seconds)
# Set to 0 to immediately reject all HS256 tokens
LEGACY_HS256_GRACE_PERIOD_SECONDS: int = int(
    os.getenv("LEGACY_HS256_GRACE_PERIOD_SECONDS", "0")
)

# Bcrypt hash prefix for migration detection
BCRYPT_HASH_PREFIX: str = "$2b$"
BCRYPT_HASH_PREFIX_ALT: str = "$2a$"
