# SEC-081: Unified Authentication Exceptions
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# Compliance: SOC 2 CC6.1, PCI-DSS 10.2.5
"""
Custom exceptions for SEC-081 Unified Authentication Module.

These exceptions provide granular error handling for authentication
operations, enabling proper audit logging and security monitoring.
"""

from typing import Optional


class AuthenticationError(Exception):
    """
    Base exception for all authentication errors.

    All authentication failures should inherit from this class
    to enable centralized error handling and audit logging.

    Attributes:
        message: Human-readable error description
        error_code: Machine-readable error code for logging
        details: Additional context (never include sensitive data)
    """

    def __init__(
        self,
        message: str,
        error_code: str = "AUTH_ERROR",
        details: Optional[dict] = None
    ):
        self.message = message
        self.error_code = error_code
        self.details = details or {}
        super().__init__(self.message)

    def to_dict(self) -> dict:
        """Convert to dictionary for logging (excludes sensitive data)."""
        return {
            "error_code": self.error_code,
            "message": self.message,
            "details": self.details,
        }


# =============================================================================
# TOKEN EXCEPTIONS
# =============================================================================

class TokenExpiredError(AuthenticationError):
    """Token has expired and cannot be used."""

    def __init__(self, message: str = "Token has expired", jti: Optional[str] = None):
        super().__init__(
            message=message,
            error_code="TOKEN_EXPIRED",
            details={"jti": jti} if jti else {}
        )


class TokenRevokedError(AuthenticationError):
    """Token has been revoked (logout, session termination)."""

    def __init__(self, message: str = "Token has been revoked", jti: Optional[str] = None):
        super().__init__(
            message=message,
            error_code="TOKEN_REVOKED",
            details={"jti": jti} if jti else {}
        )


class InvalidAlgorithmError(AuthenticationError):
    """
    Token uses a blocked or unsupported algorithm.

    This exception is raised for:
    - "none" algorithm attacks (CVE-2015-9235)
    - HS256/HS384/HS512 in multi-tenant context
    - Algorithm confusion attacks
    """

    def __init__(
        self,
        message: str = "Invalid or blocked algorithm",
        algorithm: Optional[str] = None
    ):
        super().__init__(
            message=message,
            error_code="INVALID_ALGORITHM",
            details={"algorithm": algorithm} if algorithm else {}
        )


class InvalidSignatureError(AuthenticationError):
    """Token signature verification failed."""

    def __init__(self, message: str = "Invalid token signature"):
        super().__init__(
            message=message,
            error_code="INVALID_SIGNATURE",
            details={}
        )


class InvalidClaimsError(AuthenticationError):
    """Token claims validation failed (missing required claims, invalid values)."""

    def __init__(
        self,
        message: str = "Invalid token claims",
        missing_claims: Optional[list] = None,
        invalid_claims: Optional[list] = None
    ):
        details = {}
        if missing_claims:
            details["missing_claims"] = missing_claims
        if invalid_claims:
            details["invalid_claims"] = invalid_claims
        super().__init__(
            message=message,
            error_code="INVALID_CLAIMS",
            details=details
        )


class TokenNotFoundError(AuthenticationError):
    """No token provided in request."""

    def __init__(self, message: str = "Authentication token not provided"):
        super().__init__(
            message=message,
            error_code="TOKEN_NOT_FOUND",
            details={}
        )


class KeyNotFoundError(AuthenticationError):
    """JWT signing/verification key not found."""

    def __init__(self, message: str = "JWT key not configured", key_type: str = "unknown"):
        super().__init__(
            message=message,
            error_code="KEY_NOT_FOUND",
            details={"key_type": key_type}
        )


# =============================================================================
# PASSWORD EXCEPTIONS
# =============================================================================

class PasswordHashingError(AuthenticationError):
    """Error during password hashing operation."""

    def __init__(self, message: str = "Password hashing failed"):
        super().__init__(
            message=message,
            error_code="HASH_ERROR",
            details={}
        )


class PepperNotConfiguredError(AuthenticationError):
    """
    Password pepper not configured in production.

    Per SEC-081 requirements, password pepper is REQUIRED in production
    for defense-in-depth. This exception is raised when pepper is missing.
    """

    def __init__(self, message: str = "Password pepper not configured"):
        super().__init__(
            message=message,
            error_code="PEPPER_NOT_CONFIGURED",
            details={"severity": "CRITICAL"}
        )


class PasswordVerificationError(AuthenticationError):
    """Password verification failed (wrong password)."""

    def __init__(self, message: str = "Password verification failed"):
        super().__init__(
            message=message,
            error_code="PASSWORD_MISMATCH",
            details={}
        )


class PasswordPolicyError(AuthenticationError):
    """Password does not meet policy requirements."""

    def __init__(
        self,
        message: str = "Password does not meet requirements",
        violations: Optional[list] = None
    ):
        super().__init__(
            message=message,
            error_code="PASSWORD_POLICY_VIOLATION",
            details={"violations": violations or []}
        )


# =============================================================================
# TENANT CONTEXT EXCEPTIONS
# =============================================================================

class TenantContextError(AuthenticationError):
    """Error establishing tenant context (Layer 1 failure)."""

    def __init__(
        self,
        message: str = "Failed to establish tenant context",
        org_id: Optional[str] = None
    ):
        super().__init__(
            message=message,
            error_code="TENANT_CONTEXT_ERROR",
            details={"org_id": org_id} if org_id else {}
        )


class OrganizationMismatchError(AuthenticationError):
    """Request organization doesn't match authenticated context."""

    def __init__(
        self,
        message: str = "Organization mismatch",
        expected_org_id: Optional[str] = None,
        provided_org_id: Optional[str] = None
    ):
        super().__init__(
            message=message,
            error_code="ORG_MISMATCH",
            details={
                "expected": expected_org_id,
                "provided": provided_org_id
            }
        )


# =============================================================================
# REVOCATION EXCEPTIONS
# =============================================================================

class RevocationServiceError(AuthenticationError):
    """Error communicating with revocation service (Redis)."""

    def __init__(self, message: str = "Revocation service unavailable"):
        super().__init__(
            message=message,
            error_code="REVOCATION_SERVICE_ERROR",
            details={"severity": "WARNING"}
        )
