# SEC-081: Legacy HS256 Token Support (Grace Period)
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# This module provides temporary support for legacy HS256 tokens during
# the migration grace period from HS256 to RS256. After the grace period
# expires, all HS256 tokens will be rejected.
#
# Compliance: SOC 2 CC6.1, NIST SP 800-131A
"""
Legacy HS256 Token Support for SEC-081 Migration.

This module provides a grace period for accepting legacy HS256 tokens
while the platform migrates to RS256-only authentication.

SECURITY NOTICE:
- This is TEMPORARY migration code only
- All HS256 token usage is logged at WARNING level
- After grace period expires (2025-12-11), HS256 tokens will be rejected
- Users should re-login to receive new RS256 tokens

Architecture:
    Legacy HS256 Token → verify_legacy_hs256_token() → TenantContext
                              ↓
                         [Grace Period Check]
                              ↓
                         [INTEGER org_id → UUID conversion]
                              ↓
                         [WARNING logged for monitoring]

Migration Timeline:
    - 2025-12-04: Grace period begins (SEC-081 deployment)
    - 2025-12-11: Grace period ends (7 days)
    - After 2025-12-11: HS256 tokens rejected with 401
"""

import jwt
import logging
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from .exceptions import (
    AuthenticationError,
    TokenExpiredError,
    InvalidClaimsError,
)
from .tenant_context import TenantContext

logger = logging.getLogger(__name__)

# =============================================================================
# GRACE PERIOD CONFIGURATION
# =============================================================================

# Grace period end date: December 11, 2025 00:00:00 UTC
# After this date, all HS256 tokens will be rejected
GRACE_PERIOD_END = datetime(2025, 12, 11, 0, 0, 0, tzinfo=timezone.utc)


def is_within_grace_period() -> bool:
    """
    Check if current time is within the HS256 grace period.

    Returns:
        True if within grace period, False if expired
    """
    now = datetime.now(timezone.utc)
    within_period = now < GRACE_PERIOD_END

    if not within_period:
        days_expired = (now - GRACE_PERIOD_END).days
        logger.info(
            f"SEC-081: HS256 grace period EXPIRED {days_expired} days ago "
            f"(ended {GRACE_PERIOD_END.isoformat()})"
        )

    return within_period


def get_grace_period_remaining() -> str:
    """
    Get human-readable time remaining in grace period.

    Returns:
        String describing remaining time (e.g., "5 days", "expired")
    """
    now = datetime.now(timezone.utc)
    if now >= GRACE_PERIOD_END:
        return "expired"

    delta = GRACE_PERIOD_END - now
    days = delta.days
    hours = delta.seconds // 3600

    if days > 0:
        return f"{days} day{'s' if days != 1 else ''}"
    elif hours > 0:
        return f"{hours} hour{'s' if hours != 1 else ''}"
    else:
        minutes = delta.seconds // 60
        return f"{minutes} minute{'s' if minutes != 1 else ''}"


# =============================================================================
# LEGACY HS256 TOKEN VERIFICATION
# =============================================================================


def verify_legacy_hs256_token(
    token: str,
    secret_key: str,
    algorithm: str = "HS256",
    client_ip: Optional[str] = None,
) -> TenantContext:
    """
    Verify legacy HS256 token and convert to TenantContext.

    This function provides backward compatibility for legacy HS256 tokens
    during the migration grace period. It handles the conversion of
    INTEGER organization_id to UUID format for TenantContext compatibility.

    SECURITY WARNINGS:
    - HS256 uses symmetric keys (less secure than RS256)
    - All usage is logged at WARNING level for monitoring
    - Users should re-login to receive RS256 tokens
    - This function will be removed after grace period

    Args:
        token: JWT token string (HS256 algorithm)
        secret_key: Secret key for HS256 verification
        algorithm: Expected algorithm (default: "HS256")
        client_ip: Client IP address (optional)

    Returns:
        TenantContext with converted UUID org_id

    Raises:
        TokenExpiredError: If token has expired
        InvalidClaimsError: If required claims missing
        AuthenticationError: If verification fails

    Example:
        >>> context = verify_legacy_hs256_token(
        ...     token="eyJ0eXAi...",
        ...     secret_key="your-secret-key"
        ... )
        >>> print(context.org_id)  # UUID format
        UUID('00000000-0000-0000-0000-000000000004')
    """
    # Check grace period BEFORE processing token
    if not is_within_grace_period():
        remaining = get_grace_period_remaining()
        logger.warning(
            f"SEC-081: HS256 token rejected - grace period {remaining} "
            f"(ended {GRACE_PERIOD_END.isoformat()})"
        )
        raise AuthenticationError(
            "Legacy tokens no longer accepted. Please login again to receive a new token.",
            detail={
                "grace_period_ended": GRACE_PERIOD_END.isoformat(),
                "days_expired": (datetime.now(timezone.utc) - GRACE_PERIOD_END).days,
            }
        )

    # Decode and verify HS256 token
    try:
        claims = jwt.decode(
            token,
            secret_key,
            algorithms=[algorithm],
            options={
                "verify_signature": True,
                "verify_exp": True,
                "verify_nbf": False,
                "verify_iat": False,
                "require": ["exp", "sub"],  # Minimal requirements for legacy tokens
            }
        )
    except jwt.ExpiredSignatureError as e:
        logger.warning(f"SEC-081: Legacy HS256 token expired")
        raise TokenExpiredError("Token has expired - please login again")
    except jwt.InvalidSignatureError:
        logger.warning("SEC-081: Invalid HS256 token signature")
        raise AuthenticationError("Invalid token signature")
    except jwt.PyJWTError as e:
        logger.warning(f"SEC-081: Legacy HS256 token verification failed: {e}")
        raise AuthenticationError(f"Token verification failed: {e}")

    # Validate required claims for legacy token
    required_claims = ["sub", "exp"]
    missing_claims = [c for c in required_claims if c not in claims]
    if missing_claims:
        logger.warning(f"SEC-081: Legacy token missing claims: {missing_claims}")
        raise InvalidClaimsError(
            f"Missing required claims: {missing_claims}",
            invalid_claims=missing_claims
        )

    # Extract organization_id (may be INTEGER in legacy tokens)
    org_id_raw = claims.get("organization_id")
    if org_id_raw is None:
        # Some legacy tokens may not have organization_id
        logger.warning(
            f"SEC-081: Legacy token missing organization_id - using default"
        )
        org_id_raw = 1  # Default to organization 1

    # Convert INTEGER org_id to UUID for TenantContext compatibility
    # UUID(int=N) creates deterministic UUID from integer
    if isinstance(org_id_raw, int):
        org_id_uuid = UUID(int=org_id_raw)
        logger.debug(
            f"SEC-081: Converted legacy org_id {org_id_raw} (int) → "
            f"{org_id_uuid} (UUID)"
        )
    elif isinstance(org_id_raw, str):
        try:
            # Try parsing as UUID first
            org_id_uuid = UUID(org_id_raw)
        except ValueError:
            # If not valid UUID, try as integer string
            try:
                org_id_int = int(org_id_raw)
                org_id_uuid = UUID(int=org_id_int)
                logger.debug(
                    f"SEC-081: Converted legacy org_id '{org_id_raw}' (str) → "
                    f"{org_id_uuid} (UUID)"
                )
            except ValueError:
                logger.error(f"SEC-081: Invalid org_id format: {org_id_raw}")
                raise InvalidClaimsError(
                    "Invalid organization_id format",
                    invalid_claims=["organization_id"]
                )
    else:
        org_id_uuid = UUID(str(org_id_raw))

    # Extract user_id (sub claim) - may be INTEGER or string
    user_id_raw = claims["sub"]
    if isinstance(user_id_raw, int):
        user_id_uuid = UUID(int=user_id_raw)
    elif isinstance(user_id_raw, str):
        try:
            user_id_uuid = UUID(user_id_raw)
        except ValueError:
            # Try as integer string
            try:
                user_id_uuid = UUID(int=int(user_id_raw))
            except ValueError:
                logger.error(f"SEC-081: Invalid user_id format: {user_id_raw}")
                raise InvalidClaimsError(
                    "Invalid user_id format",
                    invalid_claims=["sub"]
                )
    else:
        user_id_uuid = UUID(str(user_id_raw))

    # Extract other claims with defaults for legacy tokens
    role = claims.get("role", "user")
    permissions_raw = claims.get("permissions", [])
    if isinstance(permissions_raw, str):
        permissions_raw = [permissions_raw]
    permissions = frozenset(permissions_raw)

    # Generate session_id and jti for legacy tokens that may not have them
    session_id = claims.get("session_id", f"legacy_sess_{user_id_uuid}")
    jti = claims.get("jti", f"legacy_jti_{user_id_uuid}_{claims['iat']}")

    # Create TenantContext with converted UUIDs
    context = TenantContext(
        org_id=org_id_uuid,
        tenant_id=str(org_id_uuid),  # Use UUID string as tenant_id
        user_id=user_id_uuid,
        role=role,
        permissions=permissions,
        session_id=session_id,
        token_jti=jti,
        authenticated_at=float(claims.get("iat", datetime.now(timezone.utc).timestamp())),
        token_expires_at=float(claims["exp"]),
        auth_method="legacy_hs256",  # Mark as legacy for audit trail
        client_ip=client_ip,
    )

    # LOG WARNING: Legacy HS256 token usage for monitoring
    remaining = get_grace_period_remaining()
    logger.warning(
        f"SEC-081: Legacy HS256 token used - user should re-login for RS256 | "
        f"user_id={user_id_uuid} | "
        f"org_id={org_id_uuid} | "
        f"email={claims.get('email', 'unknown')} | "
        f"grace_period_remaining={remaining} | "
        f"expires={GRACE_PERIOD_END.isoformat()}"
    )

    return context


# =============================================================================
# MIGRATION UTILITIES
# =============================================================================


def should_reject_hs256() -> bool:
    """
    Check if HS256 tokens should be rejected (grace period expired).

    Returns:
        True if HS256 should be rejected, False if still accepted
    """
    return not is_within_grace_period()


def get_migration_status() -> dict:
    """
    Get current migration status for monitoring dashboards.

    Returns:
        Dictionary with migration status information
    """
    within_grace = is_within_grace_period()
    remaining = get_grace_period_remaining()
    now = datetime.now(timezone.utc)

    return {
        "grace_period_active": within_grace,
        "grace_period_end": GRACE_PERIOD_END.isoformat(),
        "grace_period_remaining": remaining,
        "hs256_accepted": within_grace,
        "rs256_required": not within_grace,
        "current_time": now.isoformat(),
        "migration_phase": "grace_period" if within_grace else "rs256_only",
    }
