# SEC-081: Immutable Tenant Context
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# Layer 1: Tenant Context Establishment (Four-Layer Defense Model)
# Compliance: SOC 2 CC6.1, NIST AC-3, PCI-DSS 7.1
"""
Immutable TenantContext for Layer 1 Tenant Establishment.

This class represents the authenticated context for a request, created
by TokenService.verify() and propagated through all layers of the
Four-Layer Defense-in-Depth architecture.

The context is IMMUTABLE (frozen=True) to prevent tampering after
establishment. Any attempt to modify attributes will raise FrozenInstanceError.

Usage:
    # Created by TokenService.verify()
    context = token_service.verify(jwt_token)

    # Use in route handlers
    if context.has_permission("write"):
        # Authorized for write operations
        pass

    # Pass to data access layer
    results = db_service.query(org_id=context.org_id)
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import FrozenSet, Optional, Set
from uuid import UUID
import hashlib


@dataclass(frozen=True)
class TenantContext:
    """
    Immutable tenant context for Layer 1 establishment.

    Created by TokenService.verify() from validated JWT claims.
    Propagated through middleware, routes, and data access layers.

    Attributes:
        org_id: Organization UUID (Layer 1 tenant identifier)
        tenant_id: Human-readable tenant identifier
        user_id: Authenticated user UUID
        role: User role (admin, user, viewer)
        permissions: Immutable set of permissions
        session_id: Session identifier for revocation tracking
        token_jti: JWT ID for audit trail
        authenticated_at: Unix timestamp of authentication
        token_expires_at: Token expiration timestamp
        auth_method: Authentication method used (jwt, api_key, cognito)

    Security Properties:
        - Immutable: Cannot be modified after creation
        - Hashable: Can be used in sets/dicts for caching
        - Auditable: Contains JTI for correlation with audit logs
    """

    # Required tenant identification
    org_id: UUID
    tenant_id: str
    user_id: UUID

    # Authorization attributes
    role: str
    permissions: FrozenSet[str]

    # Session tracking
    session_id: str
    token_jti: str

    # Timing metadata
    authenticated_at: float
    token_expires_at: float

    # Authentication method
    auth_method: str = "jwt"

    # Optional: IP address for geo-restriction (if captured)
    client_ip: Optional[str] = None

    def has_permission(self, permission: str) -> bool:
        """
        Check if context has a specific permission.

        Args:
            permission: Permission string to check (e.g., "write", "admin:users")

        Returns:
            True if permission is granted, False otherwise
        """
        return permission in self.permissions

    def has_any_permission(self, *permissions: str) -> bool:
        """
        Check if context has any of the specified permissions.

        Args:
            *permissions: Variable permission strings to check

        Returns:
            True if any permission is granted, False otherwise
        """
        return bool(self.permissions.intersection(permissions))

    def has_all_permissions(self, *permissions: str) -> bool:
        """
        Check if context has all of the specified permissions.

        Args:
            *permissions: Variable permission strings to check

        Returns:
            True if all permissions are granted, False otherwise
        """
        return set(permissions).issubset(self.permissions)

    def is_admin(self) -> bool:
        """
        Check if context has admin role.

        Returns:
            True if role is "admin", False otherwise
        """
        return self.role == "admin"

    def is_superadmin(self) -> bool:
        """
        Check if context has superadmin privileges.

        Returns:
            True if role is "superadmin", False otherwise
        """
        return self.role == "superadmin"

    def for_org(self, org_id: UUID) -> bool:
        """
        Validate context is for a specific organization.

        Used for Layer 2 validation to ensure requests only access
        resources within the authenticated organization.

        Args:
            org_id: Organization UUID to check

        Returns:
            True if context org_id matches, False otherwise
        """
        return self.org_id == org_id

    def is_expired(self) -> bool:
        """
        Check if the underlying token has expired.

        Returns:
            True if token is expired, False otherwise
        """
        return datetime.utcnow().timestamp() > self.token_expires_at

    def time_until_expiry(self) -> float:
        """
        Get seconds until token expiration.

        Returns:
            Seconds until expiration (negative if expired)
        """
        return self.token_expires_at - datetime.utcnow().timestamp()

    def to_audit_dict(self) -> dict:
        """
        Convert to dictionary for audit logging.

        Excludes sensitive data while preserving all information
        needed for security audit and compliance reporting.

        Returns:
            Dictionary safe for logging
        """
        return {
            "org_id": str(self.org_id),
            "tenant_id": self.tenant_id,
            "user_id": str(self.user_id),
            "role": self.role,
            "permissions": list(self.permissions),
            "session_id": self.session_id,
            "token_jti": self.token_jti,
            "auth_method": self.auth_method,
            "authenticated_at": self.authenticated_at,
            "client_ip": self.client_ip,
        }

    def fingerprint(self) -> str:
        """
        Generate a unique fingerprint for this context.

        Used for caching and deduplication. The fingerprint is
        deterministic based on the immutable context values.

        Returns:
            SHA-256 hash of context (first 16 chars)
        """
        data = f"{self.org_id}:{self.user_id}:{self.session_id}:{self.token_jti}"
        return hashlib.sha256(data.encode()).hexdigest()[:16]

    @classmethod
    def from_claims(
        cls,
        claims: dict,
        auth_method: str = "jwt",
        client_ip: Optional[str] = None
    ) -> "TenantContext":
        """
        Create TenantContext from validated JWT claims.

        This factory method is used by TokenService after successful
        JWT verification to create an immutable context.

        Args:
            claims: Validated JWT claims dictionary
            auth_method: Authentication method used
            client_ip: Client IP address (optional)

        Returns:
            Immutable TenantContext instance

        Raises:
            ValueError: If required claims are missing
        """
        # Validate required claims
        required = ["sub", "org_id", "jti", "iat", "exp"]
        missing = [c for c in required if c not in claims]
        if missing:
            raise ValueError(f"Missing required claims: {missing}")

        # Parse org_id as UUID (per SEC-081 Modification 1)
        org_id_str = claims["org_id"]
        if isinstance(org_id_str, UUID):
            org_id = org_id_str
        else:
            org_id = UUID(str(org_id_str))

        # Parse user_id as UUID
        user_id_str = claims["sub"]
        if isinstance(user_id_str, UUID):
            user_id = user_id_str
        else:
            user_id = UUID(str(user_id_str))

        # Extract permissions as frozen set
        permissions_list = claims.get("permissions", [])
        if isinstance(permissions_list, str):
            permissions_list = [permissions_list]
        permissions = frozenset(permissions_list)

        return cls(
            org_id=org_id,
            tenant_id=claims.get("tenant_id", str(org_id)),
            user_id=user_id,
            role=claims.get("role", "user"),
            permissions=permissions,
            session_id=claims.get("session_id", claims["jti"]),
            token_jti=claims["jti"],
            authenticated_at=float(claims["iat"]),
            token_expires_at=float(claims["exp"]),
            auth_method=auth_method,
            client_ip=client_ip,
        )


# Type alias for dependency injection
TenantContextType = TenantContext
