"""Add RuleFeedback table

Revision ID: be858bdecce8
Revises: de9b00ce321e
Create Date: 2025-06-10 22:05:56.383941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be858bdecce8'
down_revision: Union[str, None] = 'de9b00ce321e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('false_positive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_feedback_id'), 'rule_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_feedback_id'), table_name='rule_feedback')
    op.drop_table('rule_feedback')
    # ### end Alembic commands ###
