# RBAC Task 1: FastAPI Dependencies for Two-Tier Identity
# SEC-088: Scope-Based Access Control
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# This module provides FastAPI dependencies for the two-tier identity system:
# - Platform tier: /platform/* routes for Ascend staff
# - Tenant tier: /api/* routes for customer users
#
# Compliance: SOC 2 CC6.1, NIST AC-3, PCI-DSS 7.1
"""
RBAC Dependencies for Two-Tier Identity Architecture.

This module provides FastAPI dependencies that integrate with the
MultiPoolJWTValidator to enforce scope-based access control.

Usage:
    from dependencies_rbac import (
        get_current_user_with_scope,
        require_platform_scope,
        require_org_scope,
        get_db_for_scope,
    )

    # Platform routes (Ascend staff only)
    @router.get("/platform/orgs")
    async def list_orgs(
        current_user: TokenClaims = Depends(require_platform_scope),
        db: Session = Depends(get_db_public),
    ):
        ...

    # Tenant routes (customer users only)
    @router.get("/api/policies")
    async def list_policies(
        current_user: TokenClaims = Depends(require_org_scope),
        db: Session = Depends(get_db_for_scope),
    ):
        ...
"""

import logging
from typing import Optional, Callable
from functools import wraps

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from sqlalchemy.orm import Session
from sqlalchemy import text

from services.multi_pool_jwt_validator import (
    MultiPoolJWTValidator,
    TokenClaims,
    get_multi_pool_validator,
    InvalidTokenError,
    TokenExpiredError,
    ScopeViolationError,
    UnknownPoolError,
)

# Import existing dependencies for compatibility
try:
    from database import SessionLocal
except ImportError:
    from dependencies import SessionLocal

from security.cookies import SESSION_COOKIE_NAME

logger = logging.getLogger(__name__)

# HTTP Bearer security scheme
security = HTTPBearer(auto_error=False)


# =============================================================================
# CORE AUTHENTICATION
# =============================================================================

async def get_current_user_with_scope(
    request: Request,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> TokenClaims:
    """
    Authenticate user and return TokenClaims with scope.

    This dependency extracts the JWT from cookie or bearer header,
    validates it using the MultiPoolJWTValidator, and returns
    immutable TokenClaims with scope information.

    Returns:
        TokenClaims with scope='platform' or scope='org'

    Raises:
        HTTPException 401: If authentication fails
    """
    # Get database session for pool lookups
    db = SessionLocal()
    try:
        validator = get_multi_pool_validator(db)

        # Extract token from cookie or bearer header
        token = _extract_token(request, credentials)
        if not token:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Authentication required",
                headers={"WWW-Authenticate": "Bearer"},
            )

        # Validate token
        claims = await validator.validate_token(token)

        # Store claims in request state for downstream use
        request.state.token_claims = claims
        request.state.scope = claims.scope
        request.state.org_id = claims.org_id

        logger.info(
            f"SEC-088: User authenticated | "
            f"user_id={claims.user_id} | "
            f"scope={claims.scope} | "
            f"org_id={claims.org_id}"
        )

        return claims

    except TokenExpiredError as e:
        logger.warning(f"SEC-088: Token expired | exp={e.exp}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired - please login again",
        )

    except InvalidTokenError as e:
        logger.warning(f"SEC-088: Invalid token | error={str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token",
        )

    except UnknownPoolError as e:
        logger.warning(f"SEC-088: Unknown pool | issuer={e.issuer}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token from unknown identity provider",
        )

    except Exception as e:
        logger.error(f"SEC-088: Authentication error | error={str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication failed",
        )

    finally:
        db.close()


def _extract_token(
    request: Request,
    credentials: Optional[HTTPAuthorizationCredentials],
) -> Optional[str]:
    """
    Extract JWT token from request.

    Checks in order:
    1. HttpOnly session cookie
    2. Authorization: Bearer header

    Args:
        request: FastAPI request
        credentials: Bearer credentials if present

    Returns:
        JWT token string or None
    """
    # 1. Check session cookie first (more secure)
    cookie_token = request.cookies.get(SESSION_COOKIE_NAME)
    if cookie_token:
        logger.debug("SEC-088: Token extracted from cookie")
        return cookie_token

    # 2. Check bearer header
    if credentials and credentials.credentials:
        token = credentials.credentials
        # Verify it's a JWT (3 segments)
        if token.count('.') == 2:
            logger.debug("SEC-088: Token extracted from bearer header")
            return token

    return None


# =============================================================================
# SCOPE-BASED DEPENDENCIES
# =============================================================================

async def require_platform_scope(
    request: Request,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> TokenClaims:
    """
    Require platform scope for Ascend staff routes.

    Use this dependency for /platform/* routes that should only be
    accessible by Ascend staff (Super Admin, Support, Billing).

    Returns:
        TokenClaims with scope='platform'

    Raises:
        HTTPException 401: If not authenticated
        HTTPException 403: If not platform scope
    """
    claims = await get_current_user_with_scope(request, credentials)

    if claims.scope != "platform":
        logger.warning(
            f"SEC-088: Platform scope required | "
            f"user_id={claims.user_id} | "
            f"actual_scope={claims.scope}"
        )
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Platform access required - this route is for Ascend staff only",
        )

    if claims.org_id is not None:
        logger.warning(
            f"SEC-088: Platform user has org_id (violation) | "
            f"user_id={claims.user_id} | "
            f"org_id={claims.org_id}"
        )
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Platform users cannot have organization context",
        )

    logger.debug(f"SEC-088: Platform scope verified | user_id={claims.user_id}")
    return claims


async def require_org_scope(
    request: Request,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> TokenClaims:
    """
    Require org scope for customer routes.

    Use this dependency for /api/* routes that should only be
    accessible by customer users within their organization.

    Returns:
        TokenClaims with scope='org' and org_id

    Raises:
        HTTPException 401: If not authenticated
        HTTPException 403: If not org scope or missing org_id
    """
    claims = await get_current_user_with_scope(request, credentials)

    if claims.scope != "org":
        logger.warning(
            f"SEC-088: Org scope required | "
            f"user_id={claims.user_id} | "
            f"actual_scope={claims.scope}"
        )
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Organization access required - this route is for customer users",
        )

    if claims.org_id is None:
        logger.warning(
            f"SEC-088: Org user missing org_id (violation) | "
            f"user_id={claims.user_id}"
        )
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Organization context required",
        )

    logger.debug(
        f"SEC-088: Org scope verified | "
        f"user_id={claims.user_id} | "
        f"org_id={claims.org_id}"
    )
    return claims


# =============================================================================
# DATABASE DEPENDENCIES WITH SCOPE
# =============================================================================

def get_db_for_scope(
    request: Request,
    claims: TokenClaims = Depends(get_current_user_with_scope),
) -> Session:
    """
    Get database session with appropriate RLS based on scope.

    For platform users: No RLS (but they only access metadata routes)
    For org users: RLS activated with org_id

    This integrates with PostgreSQL Row-Level Security policies.

    Args:
        request: FastAPI request
        claims: Validated token claims

    Yields:
        Database session with appropriate RLS context
    """
    db = SessionLocal()
    try:
        if claims.scope == "org" and claims.org_id:
            # Activate RLS for tenant users
            try:
                db.execute(
                    text("SET app.current_organization_id = :org_id"),
                    {"org_id": claims.org_id}
                )
                logger.info(
                    f"SEC-088: RLS activated | "
                    f"org_id={claims.org_id} | "
                    f"user_id={claims.user_id}"
                )
            except Exception as e:
                logger.error(
                    f"SEC-088: Failed to activate RLS | "
                    f"org_id={claims.org_id} | "
                    f"error={str(e)}"
                )
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail="Failed to activate security policies",
                )
        else:
            # Platform users: no RLS (but they only access metadata)
            logger.debug(
                f"SEC-088: No RLS (platform scope) | "
                f"user_id={claims.user_id}"
            )

        yield db

    except HTTPException:
        db.rollback()
        raise
    except Exception as e:
        logger.error(f"SEC-088: Database error | error={str(e)}")
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Database error",
        )
    finally:
        db.close()


def get_db_platform() -> Session:
    """
    Get database session for platform routes (no RLS).

    Use this for /platform/* routes where platform users need
    to query across organizations (metadata only).

    Yields:
        Database session without RLS
    """
    db = SessionLocal()
    try:
        logger.debug("SEC-088: Platform DB session created (no RLS)")
        yield db
    except HTTPException:
        db.rollback()
        raise
    except Exception as e:
        logger.error(f"SEC-088: Platform DB error | error={str(e)}")
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Database error",
        )
    finally:
        db.close()


# =============================================================================
# BACKWARD COMPATIBILITY
# =============================================================================

def claims_to_user_dict(claims: TokenClaims) -> dict:
    """
    Convert TokenClaims to legacy user dict format.

    Provides backward compatibility with existing code that expects
    the old dict-style user information.

    Args:
        claims: TokenClaims from validation

    Returns:
        Dict in legacy format with user_id, email, role, organization_id
    """
    return {
        "user_id": claims.user_id,
        "sub": claims.sub,
        "email": claims.email,
        "role": None,  # Role comes from database lookup, not token
        "organization_id": claims.org_id,
        "org_id": claims.org_id,
        "scope": claims.scope,
        "is_platform_user": claims.is_platform_user,
        "cognito_groups": claims.cognito_groups,
        "auth_method": "cognito",
        "pool_id": claims.pool_id,
    }


async def get_current_user_legacy(
    request: Request,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> dict:
    """
    Get current user in legacy dict format.

    Use this for gradual migration of existing endpoints.

    Returns:
        Dict with user information (legacy format)
    """
    claims = await get_current_user_with_scope(request, credentials)
    return claims_to_user_dict(claims)


# =============================================================================
# ROLE-BASED GUARDS
# =============================================================================

def require_platform_role(*roles: str):
    """
    Decorator factory for platform role requirements.

    Args:
        roles: Allowed platform roles (Super Admin, Support, Billing)

    Usage:
        @router.get("/platform/admin")
        @require_platform_role("Super Admin")
        async def admin_route(claims: TokenClaims = Depends(require_platform_scope)):
            ...
    """
    def decorator(func: Callable):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            # Extract claims from kwargs (assumes require_platform_scope dependency)
            claims = None
            for key, value in kwargs.items():
                if isinstance(value, TokenClaims):
                    claims = value
                    break

            if not claims:
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail="TokenClaims not found in request",
                )

            # Check role via Cognito groups
            user_roles = claims.cognito_groups
            if not any(role in user_roles for role in roles):
                logger.warning(
                    f"SEC-088: Platform role denied | "
                    f"user_id={claims.user_id} | "
                    f"required={roles} | "
                    f"actual={user_roles}"
                )
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN,
                    detail=f"Required role: {', '.join(roles)}",
                )

            return await func(*args, **kwargs)
        return wrapper
    return decorator


def require_org_role(*roles: str):
    """
    Decorator factory for tenant role requirements.

    Args:
        roles: Allowed tenant roles (Owner, Admin, Approver, Operator, Viewer)

    Usage:
        @router.post("/api/policies")
        @require_org_role("Owner", "Admin")
        async def create_policy(claims: TokenClaims = Depends(require_org_scope)):
            ...
    """
    def decorator(func: Callable):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            # Extract claims from kwargs
            claims = None
            for key, value in kwargs.items():
                if isinstance(value, TokenClaims):
                    claims = value
                    break

            if not claims:
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail="TokenClaims not found in request",
                )

            # Check role via Cognito groups
            user_roles = claims.cognito_groups
            if not any(role in user_roles for role in roles):
                logger.warning(
                    f"SEC-088: Org role denied | "
                    f"user_id={claims.user_id} | "
                    f"org_id={claims.org_id} | "
                    f"required={roles} | "
                    f"actual={user_roles}"
                )
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN,
                    detail=f"Required role: {', '.join(roles)}",
                )

            return await func(*args, **kwargs)
        return wrapper
    return decorator


# =============================================================================
# AUDIT LOGGING
# =============================================================================

async def log_access(
    request: Request,
    claims: TokenClaims,
    action: str,
    resource: str,
    resource_id: Optional[str] = None,
    decision: str = "allowed",
    reason: Optional[str] = None,
) -> None:
    """
    Log access decision for compliance audit trail.

    Args:
        request: FastAPI request
        claims: User token claims
        action: Action being performed (read, create, update, delete)
        resource: Resource type (policies, agents, workflows, etc.)
        resource_id: Specific resource ID if applicable
        decision: 'allowed' or 'denied'
        reason: Reason for decision
    """
    logger.info(
        f"SEC-088: ACCESS_LOG | "
        f"user_id={claims.user_id} | "
        f"org_id={claims.org_id} | "
        f"scope={claims.scope} | "
        f"action={action} | "
        f"resource={resource} | "
        f"resource_id={resource_id} | "
        f"decision={decision} | "
        f"reason={reason} | "
        f"path={request.url.path} | "
        f"method={request.method}"
    )
