"""
RBAC-003/004: Platform User Authentication Dependencies
Generated by Ascend Engineering Team
Application Owner: OW-KAI Technologies, Inc.

Provides scope-based authentication dependencies:
- get_current_platform_user: For platform-only routes (scope='platform')
- get_current_org_user: For tenant-only routes (scope='org')
- get_current_user_any_scope: For routes accessible by both

Security Standards: SOC 2 CC6.1, NIST AC-2, PCI-DSS 7.1
"""

import os
import logging
from typing import Optional
from datetime import datetime

from fastapi import Depends, HTTPException, Request, status
from sqlalchemy.orm import Session

from database import get_db
from models import User

logger = logging.getLogger("enterprise.platform_auth")

# Feature flag for multi-pool auth
ENABLE_TWO_POOL_AUTH = os.getenv("ENABLE_TWO_POOL_AUTH", "false").lower() == "true"


# =============================================================================
# PLATFORM USER AUTHENTICATION
# =============================================================================

async def get_current_platform_user(
    request: Request,
    db: Session = Depends(get_db)
) -> dict:
    """
    Authenticate platform users ONLY (Ascend internal staff).

    This dependency:
    1. Validates JWT from platform Cognito pool
    2. Verifies scope='platform' in token
    3. Returns user context without organization_id
    4. Creates/updates platform user record in database

    Use for: Admin dashboards, platform management, support tools

    Returns:
        dict: Platform user context with scope='platform', org_id=None

    Raises:
        HTTPException 401: If not authenticated
        HTTPException 403: If authenticated but not a platform user
    """
    if not ENABLE_TWO_POOL_AUTH:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Platform authentication not enabled"
        )

    from dependencies_cognito import validate_cognito_token

    # Extract token
    auth_header = request.headers.get("Authorization", "")
    if not auth_header.startswith("Bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or invalid Authorization header",
            headers={"WWW-Authenticate": "Bearer"}
        )

    token = auth_header[7:]

    try:
        # Validate token with multi-pool support
        token_payload = validate_cognito_token(token, db=db)

        # Check scope
        scope = token_payload.get("scope", "org")
        if scope != "platform":
            logger.warning(f"Non-platform user attempted platform route: {token_payload.get('email')}")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="This route requires platform user access"
            )

        # Get or create platform user in database
        cognito_user_id = token_payload.get("cognito_user_id")
        email = token_payload.get("email")

        user = db.query(User).filter(
            User.cognito_user_id == cognito_user_id
        ).first()

        if not user:
            # Create new platform user
            user = db.query(User).filter(
                User.email == email,
                User.is_platform_user == True
            ).first()

            if not user:
                # Auto-create platform user on first login
                user = User(
                    email=email,
                    cognito_user_id=cognito_user_id,
                    organization_id=None,  # Platform users have no org
                    scope="platform",
                    is_platform_user=True,
                    role="platform_admin",
                    is_active=True,
                    created_at=datetime.utcnow()
                )
                db.add(user)
                db.commit()
                db.refresh(user)
                logger.info(f"Created platform user: {email}")
            else:
                # Link existing platform user to Cognito
                user.cognito_user_id = cognito_user_id
                db.commit()
                logger.info(f"Linked platform user to Cognito: {email}")

        # Update last login
        user.last_login = datetime.utcnow()
        db.commit()

        # Return platform user context
        return {
            "user_id": user.id,
            "email": user.email,
            "cognito_user_id": cognito_user_id,
            "scope": "platform",
            "organization_id": None,
            "role": user.role,
            "is_platform_user": True,
            "pool_source": token_payload.get("pool_source"),
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Platform authentication failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token"
        )


async def get_current_org_user(
    request: Request,
    db: Session = Depends(get_db)
) -> dict:
    """
    Authenticate organization/tenant users ONLY.

    This dependency:
    1. Validates JWT from org-specific Cognito pool
    2. Verifies scope='org' in token
    3. Requires organization_id in token/claims
    4. Sets PostgreSQL RLS context for multi-tenancy

    Use for: All tenant-facing routes (existing behavior)

    Returns:
        dict: User context with organization_id

    Raises:
        HTTPException 401: If not authenticated
        HTTPException 403: If authenticated but not an org user
    """
    from dependencies_cognito import get_current_user_cognito

    # Use existing Cognito auth (handles org users)
    user_context = await get_current_user_cognito(request, db)

    # Verify this is an org user (not platform)
    scope = user_context.get("scope", "org")
    if scope == "platform":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This route requires organization user access"
        )

    return user_context


async def get_current_user_any_scope(
    request: Request,
    db: Session = Depends(get_db)
) -> dict:
    """
    Authenticate any user (platform OR organization).

    Use for: Routes accessible by both platform and org users.

    Returns:
        dict: User context (with or without organization_id based on scope)
    """
    auth_header = request.headers.get("Authorization", "")
    if not auth_header.startswith("Bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or invalid Authorization header",
            headers={"WWW-Authenticate": "Bearer"}
        )

    # Try platform auth first (if enabled)
    if ENABLE_TWO_POOL_AUTH:
        try:
            from dependencies_cognito import validate_cognito_token
            token = auth_header[7:]
            token_payload = validate_cognito_token(token, db=db)

            scope = token_payload.get("scope", "org")

            if scope == "platform":
                # Platform user path
                return await get_current_platform_user(request, db)
            else:
                # Org user path
                return await get_current_org_user(request, db)

        except HTTPException as e:
            if e.status_code == 403:
                # Scope mismatch, re-raise
                raise
            # Auth failed, try org auth
            pass

    # Fallback to org auth
    return await get_current_org_user(request, db)


# =============================================================================
# SCOPE VALIDATION HELPERS
# =============================================================================

def require_platform_scope(user_context: dict) -> None:
    """
    Validate that user has platform scope.

    Use in routes to add additional scope checks.

    Raises:
        HTTPException 403: If user is not platform scope
    """
    if user_context.get("scope") != "platform":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Platform access required"
        )


def require_org_scope(user_context: dict) -> None:
    """
    Validate that user has organization scope.

    Use in routes to add additional scope checks.

    Raises:
        HTTPException 403: If user is not org scope
    """
    if user_context.get("scope") != "org":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Organization access required"
        )


def get_org_id_or_none(user_context: dict) -> Optional[int]:
    """
    Get organization_id from user context, or None for platform users.

    Returns:
        int: Organization ID for org users
        None: For platform users
    """
    return user_context.get("organization_id")


def require_org_id(user_context: dict) -> int:
    """
    Get organization_id, raising error if not present.

    Use in routes that require an organization context.

    Returns:
        int: Organization ID

    Raises:
        HTTPException 403: If no organization_id (platform user)
    """
    org_id = user_context.get("organization_id")
    if org_id is None:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This route requires organization context"
        )
    return org_id
