# SEC-081: Unified Authentication Module Tests
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# Evidence tests for:
# - Algorithm confusion attack prevention (CVE-2015-9235)
# - bcrypt → Argon2id password migration
# - RS256 token creation and verification
# - Password pepper defense-in-depth
#
# Run with: pytest tests/test_sec081_unified_auth.py -v

import pytest
import jwt
import hashlib
import os
import sys
from datetime import datetime, timedelta
from uuid import uuid4, UUID

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services.unified_auth.constants import (
    ALGORITHM,
    BLOCKED_ALGORITHMS,
    ISSUER,
    AUDIENCES,
)
from services.unified_auth.exceptions import (
    InvalidAlgorithmError,
    InvalidSignatureError,
    TokenExpiredError,
    PepperNotConfiguredError,
)
from services.unified_auth.tenant_context import TenantContext


# =============================================================================
# TEST FIXTURES
# =============================================================================

@pytest.fixture
def rsa_keypair():
    """Generate RSA-2048 key pair for testing."""
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.backends import default_backend

    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend()
    )

    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    ).decode("utf-8")

    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    ).decode("utf-8")

    return {"private": private_pem, "public": public_pem}


@pytest.fixture
def token_service(rsa_keypair):
    """Create TokenService with test keys."""
    from services.token_service import TokenService
    from services.revocation_service import RevocationService

    revocation = RevocationService(use_memory=True)
    return TokenService(
        private_key=rsa_keypair["private"],
        public_key=rsa_keypair["public"],
        revocation_service=revocation,
    )


@pytest.fixture
def password_service():
    """Create PasswordService with test pepper."""
    os.environ["ENVIRONMENT"] = "development"
    os.environ["ASCEND_AUTH_PASSWORD_PEPPER"] = "test-pepper-for-unit-tests-only"

    from services.password_service import PasswordService
    return PasswordService()


# =============================================================================
# ALGORITHM CONFUSION ATTACK TESTS (SEC-081 Evidence Requirement)
# =============================================================================

class TestAlgorithmConfusionPrevention:
    """
    Tests for CVE-2015-9235 algorithm confusion attack prevention.

    Attack Vector:
    1. Attacker obtains public key (often exposed in JWKS endpoint)
    2. Attacker creates HS256 token using public key as HMAC secret
    3. Vulnerable servers accept token if they use public key for verification

    Expected Behavior:
    - TokenService MUST reject HS256 tokens
    - TokenService MUST reject "none" algorithm tokens
    - TokenService MUST only accept RS256 tokens
    """

    def test_rejects_hs256_token_signed_with_public_key(self, rsa_keypair, token_service):
        """
        CRITICAL TEST: Verify algorithm confusion attack is blocked.

        This test creates an HS256 token using a regular secret and
        verifies that TokenService rejects it (even if signature is valid
        for HS256, we only accept RS256).

        Note: Modern PyJWT prevents using RSA keys as HMAC secrets,
        so we test that ANY HS256 token is rejected regardless of secret.
        """
        # Create HS256 token with a regular secret
        claims = {
            "iss": ISSUER,
            "aud": AUDIENCES,
            "sub": str(uuid4()),
            "org_id": str(uuid4()),
            "exp": int((datetime.utcnow() + timedelta(hours=1)).timestamp()),
            "iat": int(datetime.utcnow().timestamp()),
            "jti": "attack_token_123",
            "type": "access",
        }

        # Sign with HS256 using any secret (simulating attack where
        # attacker tries to use HS256 instead of RS256)
        malicious_token = jwt.encode(
            claims,
            "any-secret-key",  # Attacker's secret
            algorithm="HS256"
        )

        # TokenService MUST reject this token because it's HS256
        with pytest.raises(InvalidAlgorithmError) as exc_info:
            token_service.verify(malicious_token)

        assert "HS256" in str(exc_info.value) or "blocked" in str(exc_info.value).lower()
        print(f"✅ HS256 token BLOCKED (only RS256 allowed): {exc_info.value}")

    def test_rejects_none_algorithm_token(self, token_service):
        """
        CRITICAL TEST: Verify "none" algorithm is blocked.

        The "none" algorithm attack allows tokens without signatures.
        TokenService MUST reject all tokens with "none" algorithm.
        """
        # Create unsigned token with "none" algorithm
        # We have to manually construct this since PyJWT blocks it
        import base64
        import json

        header = base64.urlsafe_b64encode(
            json.dumps({"alg": "none", "typ": "JWT"}).encode()
        ).rstrip(b"=").decode()

        claims = {
            "iss": ISSUER,
            "aud": AUDIENCES,
            "sub": str(uuid4()),
            "org_id": str(uuid4()),
            "exp": int((datetime.utcnow() + timedelta(hours=1)).timestamp()),
            "iat": int(datetime.utcnow().timestamp()),
            "jti": "none_attack_123",
            "type": "access",
        }

        payload = base64.urlsafe_b64encode(
            json.dumps(claims).encode()
        ).rstrip(b"=").decode()

        # Token with empty signature
        none_token = f"{header}.{payload}."

        # TokenService MUST reject this token
        with pytest.raises(InvalidAlgorithmError) as exc_info:
            token_service.verify(none_token)

        assert "none" in str(exc_info.value).lower() or "blocked" in str(exc_info.value).lower()
        print(f"✅ 'none' algorithm attack BLOCKED: {exc_info.value}")

    def test_accepts_valid_rs256_token(self, token_service):
        """
        Verify valid RS256 tokens are accepted.
        """
        user_id = uuid4()
        org_id = uuid4()

        # Create valid RS256 token
        token = token_service.create_access_token(
            user_id=user_id,
            org_id=org_id,
            role="admin",
            permissions=["read", "write"],
        )

        # Verify token
        context = token_service.verify(token)

        assert context.user_id == user_id
        assert context.org_id == org_id
        assert context.role == "admin"
        assert "read" in context.permissions
        print(f"✅ Valid RS256 token accepted: jti={context.token_jti}")

    def test_blocked_algorithms_list(self):
        """Verify all dangerous algorithms are in blocked list."""
        dangerous = ["none", "None", "NONE", "", "HS256", "HS384", "HS512"]
        for alg in dangerous:
            assert alg in BLOCKED_ALGORITHMS, f"Algorithm '{alg}' should be blocked"
        print(f"✅ All dangerous algorithms blocked: {dangerous}")


# =============================================================================
# BCRYPT TO ARGON2ID MIGRATION TESTS (SEC-081 Evidence Requirement)
# =============================================================================

class TestPasswordMigration:
    """
    Tests for bcrypt → Argon2id password migration.

    The PasswordService must:
    1. Verify legacy bcrypt hashes
    2. Detect bcrypt hashes as needing rehash
    3. Transparently upgrade to Argon2id on verify
    """

    def test_hashes_with_argon2id(self, password_service):
        """Verify new passwords are hashed with Argon2id."""
        password = "SecurePassword123!"
        hashed = password_service.hash(password)

        assert hashed.startswith("$argon2id$"), f"Expected Argon2id hash, got: {hashed[:20]}"
        print(f"✅ Password hashed with Argon2id: {hashed[:40]}...")

    def test_verifies_argon2id_hash(self, password_service):
        """Verify Argon2id hashes can be verified."""
        password = "MySecretPassword456!"
        hashed = password_service.hash(password)

        assert password_service.verify(password, hashed)
        assert not password_service.verify("WrongPassword", hashed)
        print("✅ Argon2id verification working correctly")

    def test_detects_bcrypt_needs_rehash(self, password_service):
        """Verify bcrypt hashes are detected as needing rehash."""
        try:
            import bcrypt
        except ImportError:
            pytest.skip("bcrypt not installed")

        # Create legacy bcrypt hash
        password = "LegacyPassword789!"
        bcrypt_hash = bcrypt.hashpw(
            password.encode("utf-8"),
            bcrypt.gensalt(rounds=12)
        ).decode("utf-8")

        # Should detect as needing rehash
        assert password_service.needs_rehash(bcrypt_hash)
        print(f"✅ bcrypt hash detected as needing rehash: {bcrypt_hash[:20]}...")

    def test_verifies_legacy_bcrypt_direct(self, password_service):
        """Verify direct bcrypt hashes (core/security.py pattern)."""
        try:
            import bcrypt
        except ImportError:
            pytest.skip("bcrypt not installed")

        password = "DirectBcryptPassword!"
        bcrypt_hash = bcrypt.hashpw(
            password.encode("utf-8"),
            bcrypt.gensalt(rounds=12)
        ).decode("utf-8")

        assert password_service.verify(password, bcrypt_hash)
        print("✅ Direct bcrypt hash verified successfully")

    def test_verifies_legacy_sha256_bcrypt(self, password_service):
        """Verify SHA-256+bcrypt hashes (auth_utils.py pattern)."""
        try:
            import bcrypt
        except ImportError:
            pytest.skip("bcrypt not installed")

        password = "SHA256BcryptPassword!"

        # Create SHA-256 + bcrypt hash (legacy pattern)
        sha_digest = hashlib.sha256(password.encode("utf-8")).hexdigest()
        bcrypt_hash = bcrypt.hashpw(
            sha_digest.encode("utf-8"),
            bcrypt.gensalt(rounds=12)
        ).decode("utf-8")

        assert password_service.verify(password, bcrypt_hash)
        print("✅ SHA-256+bcrypt hash verified successfully")

    def test_verify_and_upgrade_returns_new_hash(self, password_service):
        """Verify verify_and_upgrade returns new Argon2id hash for bcrypt."""
        try:
            import bcrypt
        except ImportError:
            pytest.skip("bcrypt not installed")

        password = "UpgradeMe123!"

        # Create legacy bcrypt hash
        bcrypt_hash = bcrypt.hashpw(
            password.encode("utf-8"),
            bcrypt.gensalt(rounds=12)
        ).decode("utf-8")

        # Verify and upgrade
        is_valid, new_hash = password_service.verify_and_upgrade(password, bcrypt_hash)

        assert is_valid, "Password should be valid"
        assert new_hash is not None, "New hash should be returned"
        assert new_hash.startswith("$argon2id$"), "New hash should be Argon2id"
        print(f"✅ Password upgraded: bcrypt → Argon2id")
        print(f"   Old: {bcrypt_hash[:30]}...")
        print(f"   New: {new_hash[:40]}...")


# =============================================================================
# TENANT CONTEXT TESTS
# =============================================================================

class TestTenantContext:
    """Tests for immutable TenantContext."""

    def test_context_is_immutable(self):
        """Verify TenantContext cannot be modified after creation."""
        context = TenantContext(
            org_id=uuid4(),
            tenant_id="acme-corp",
            user_id=uuid4(),
            role="admin",
            permissions=frozenset(["read", "write"]),
            session_id="sess_123",
            token_jti="tok_456",
            authenticated_at=datetime.utcnow().timestamp(),
            token_expires_at=(datetime.utcnow() + timedelta(hours=1)).timestamp(),
        )

        # Attempting to modify should raise FrozenInstanceError
        with pytest.raises(Exception):  # dataclass FrozenInstanceError
            context.role = "user"

        print("✅ TenantContext is immutable")

    def test_context_from_claims(self):
        """Test creating TenantContext from JWT claims."""
        org_id = uuid4()
        user_id = uuid4()

        claims = {
            "sub": str(user_id),
            "org_id": str(org_id),
            "tenant_id": "test-tenant",
            "role": "admin",
            "permissions": ["read", "write", "admin"],
            "session_id": "sess_test",
            "jti": "tok_test",
            "iat": int(datetime.utcnow().timestamp()),
            "exp": int((datetime.utcnow() + timedelta(hours=1)).timestamp()),
        }

        context = TenantContext.from_claims(claims)

        assert context.org_id == org_id
        assert context.user_id == user_id
        assert context.role == "admin"
        assert "write" in context.permissions
        print("✅ TenantContext.from_claims() working correctly")

    def test_org_id_is_uuid(self, token_service):
        """Verify org_id in TenantContext is UUID type."""
        token = token_service.create_access_token(
            user_id=uuid4(),
            org_id=uuid4(),
            role="user",
        )

        context = token_service.verify(token)

        assert isinstance(context.org_id, UUID), f"org_id should be UUID, got {type(context.org_id)}"
        print(f"✅ org_id is UUID type: {context.org_id}")


# =============================================================================
# TOKEN REVOCATION TESTS
# =============================================================================

class TestTokenRevocation:
    """Tests for token revocation functionality."""

    def test_revoked_token_is_rejected(self, token_service):
        """Verify revoked tokens are rejected."""
        user_id = uuid4()
        org_id = uuid4()

        # Create token
        token = token_service.create_access_token(
            user_id=user_id,
            org_id=org_id,
            role="user",
        )

        # Verify token works
        context = token_service.verify(token)
        assert context.user_id == user_id

        # Revoke token
        token_service.revoke(token)

        # Token should now be rejected
        from services.unified_auth.exceptions import TokenRevokedError
        with pytest.raises(TokenRevokedError):
            token_service.verify(token)

        print("✅ Revoked token rejected successfully")


# =============================================================================
# PEPPER VALIDATION TESTS
# =============================================================================

class TestPasswordPepper:
    """Tests for password pepper defense-in-depth."""

    def test_pepper_changes_hash(self):
        """Verify pepper produces different hash than no pepper."""
        # Import fresh to avoid caching
        import importlib
        import services.password_service as ps_module

        # Clear AWS credentials to force local-only mode
        aws_vars = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"]
        saved_aws = {k: os.environ.pop(k, None) for k in aws_vars}

        try:
            importlib.reload(ps_module)

            # Without pepper
            os.environ["ENVIRONMENT"] = "development"
            if "ASCEND_AUTH_PASSWORD_PEPPER" in os.environ:
                del os.environ["ASCEND_AUTH_PASSWORD_PEPPER"]

            importlib.reload(ps_module)
            service_no_pepper = ps_module.PasswordService()
            pepper_1 = service_no_pepper._pepper

            # With pepper
            os.environ["ASCEND_AUTH_PASSWORD_PEPPER"] = "my-secret-pepper"
            importlib.reload(ps_module)
            service_with_pepper = ps_module.PasswordService()
            pepper_2 = service_with_pepper._pepper

            # Verify pepper is being used by checking the service state
            assert pepper_1 is None, f"Expected no pepper, got: {pepper_1}"
            assert pepper_2 == "my-secret-pepper", f"Expected pepper, got: {pepper_2}"
            print("✅ Pepper configuration verified")

        finally:
            # Restore AWS credentials
            for k, v in saved_aws.items():
                if v is not None:
                    os.environ[k] = v

    def test_hash_without_pepper_fails_with_pepper(self):
        """Verify hash created without pepper cannot be verified with pepper."""
        # Import fresh to avoid caching
        import importlib
        import services.password_service as ps_module

        # Clear AWS credentials to force local-only mode
        aws_vars = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"]
        saved_aws = {k: os.environ.pop(k, None) for k in aws_vars}

        try:
            password = "TestPassword456!"

            # Create hash without pepper
            os.environ["ENVIRONMENT"] = "development"
            if "ASCEND_AUTH_PASSWORD_PEPPER" in os.environ:
                del os.environ["ASCEND_AUTH_PASSWORD_PEPPER"]

            importlib.reload(ps_module)
            service_no_pepper = ps_module.PasswordService()
            hash_no_pepper = service_no_pepper.hash(password)

            # Try to verify with pepper (should fail)
            os.environ["ASCEND_AUTH_PASSWORD_PEPPER"] = "different-pepper"
            importlib.reload(ps_module)
            service_with_pepper = ps_module.PasswordService()

            # Verification should fail because pepper changes the input
            is_valid = service_with_pepper.verify(password, hash_no_pepper)
            assert not is_valid, "Hash without pepper should not verify with pepper"
            print("✅ Pepper provides defense-in-depth protection")

        finally:
            # Restore AWS credentials
            for k, v in saved_aws.items():
                if v is not None:
                    os.environ[k] = v


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
