# RBAC Task 6: Permission Check API Routes
# SEC-088: Frontend Permission Integration
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# These routes enable frontend permission checking by calling
# the backend PermissionService.
#
# Compliance: SOC 2 CC6.1, NIST AC-3, PCI-DSS 7.1
"""
Permission Check API Routes.

Provides endpoints for:
- Checking single permission
- Checking multiple permissions (batch)
- Getting all user permissions
- Getting role hierarchy

Usage (Frontend):
    const { hasPermission } = usePermissions();
    if (hasPermission('policies', 'create')) {
        // Show create button
    }
"""

import logging
from typing import List, Dict, Optional
from pydantic import BaseModel

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from dependencies import get_current_user, get_db
from services.permission_service import (
    PermissionService,
    get_permission_service,
    PLATFORM_PERMISSIONS,
    TENANT_PERMISSIONS,
    PlatformRole,
    TenantRole,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/permissions", tags=["Permissions"])


# =============================================================================
# REQUEST/RESPONSE MODELS
# =============================================================================

class PermissionCheckRequest(BaseModel):
    """Request to check a single permission."""
    resource: str
    action: str
    resource_id: Optional[str] = None


class PermissionCheckResponse(BaseModel):
    """Response for single permission check."""
    allowed: bool
    resource: str
    action: str
    resource_id: Optional[str] = None


class BatchPermissionCheckRequest(BaseModel):
    """Request to check multiple permissions."""
    permissions: List[PermissionCheckRequest]


class BatchPermissionCheckResponse(BaseModel):
    """Response for batch permission check."""
    results: Dict[str, bool]  # "resource:action" -> allowed


class UserPermissionsResponse(BaseModel):
    """Response with all user permissions."""
    user_id: str
    scope: str
    roles: List[str]
    permissions: Dict[str, List[str]]  # resource -> actions


# =============================================================================
# ENDPOINTS
# =============================================================================

@router.post("/check", response_model=PermissionCheckResponse)
async def check_permission(
    request: PermissionCheckRequest,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Check if current user has a specific permission.

    This is the primary endpoint for frontend permission checks.
    Called by the frontend hasPermission() hook.

    Returns:
        PermissionCheckResponse with allowed=true/false
    """
    service = get_permission_service(db)

    allowed = await service.has_permission(
        user=current_user,
        resource=request.resource,
        action=request.action,
        resource_id=request.resource_id,
    )

    logger.debug(
        f"SEC-088: Permission check | "
        f"user_id={current_user.get('user_id')} | "
        f"resource={request.resource} | "
        f"action={request.action} | "
        f"allowed={allowed}"
    )

    return PermissionCheckResponse(
        allowed=allowed,
        resource=request.resource,
        action=request.action,
        resource_id=request.resource_id,
    )


@router.post("/check-batch", response_model=BatchPermissionCheckResponse)
async def check_permissions_batch(
    request: BatchPermissionCheckRequest,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Check multiple permissions in a single request.

    More efficient than multiple single checks for frontend
    components that need several permissions.

    Returns:
        Dict mapping "resource:action" to allowed boolean
    """
    service = get_permission_service(db)
    results = {}

    for perm in request.permissions:
        key = f"{perm.resource}:{perm.action}"
        allowed = await service.has_permission(
            user=current_user,
            resource=perm.resource,
            action=perm.action,
            resource_id=perm.resource_id,
        )
        results[key] = allowed

    logger.info(
        f"SEC-088: Batch permission check | "
        f"user_id={current_user.get('user_id')} | "
        f"count={len(request.permissions)} | "
        f"allowed={sum(1 for v in results.values() if v)}/{len(results)}"
    )

    return BatchPermissionCheckResponse(results=results)


@router.get("/me", response_model=UserPermissionsResponse)
async def get_my_permissions(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Get all permissions for the current user.

    Returns complete permission set based on user's scope and roles.
    Frontend can cache this to avoid repeated API calls.

    Returns:
        UserPermissionsResponse with all permissions
    """
    service = get_permission_service(db)

    user_id = str(current_user.get("user_id", "unknown"))  # SEC-098: Convert to string for Pydantic
    scope = current_user.get("scope", "org")
    roles = current_user.get("cognito_groups", []) or [current_user.get("role", "Viewer")]
    permissions = service.get_user_permissions(current_user)

    logger.info(
        f"SEC-088: Get user permissions | "
        f"user_id={user_id} | "
        f"scope={scope} | "
        f"roles={roles}"
    )

    return UserPermissionsResponse(
        user_id=user_id,
        scope=scope,
        roles=roles,
        permissions=permissions,
    )


@router.get("/roles")
async def get_available_roles(
    current_user: dict = Depends(get_current_user),
):
    """
    Get available roles for the current scope.

    Returns role hierarchy and permission matrix.
    """
    scope = current_user.get("scope", "org")

    if scope == "platform":
        roles = [r.value for r in PlatformRole]
        permissions = {
            role: perms for role, perms in PLATFORM_PERMISSIONS.items()
        }
    else:
        roles = [r.value for r in TenantRole]
        permissions = {
            role.value: perms for role, perms in TENANT_PERMISSIONS.items()
        }

    return {
        "scope": scope,
        "roles": roles,
        "permissions": permissions,
    }


@router.get("/resources")
async def get_available_resources(
    current_user: dict = Depends(get_current_user),
):
    """
    Get available resources and actions for the current scope.

    Useful for UI permission configuration screens.
    """
    scope = current_user.get("scope", "org")

    if scope == "platform":
        # Get unique resources from platform permissions
        resources = set()
        for role_perms in PLATFORM_PERMISSIONS.values():
            resources.update(role_perms.keys())

        # Get all actions per resource
        resource_actions = {}
        for resource in resources:
            actions = set()
            for role_perms in PLATFORM_PERMISSIONS.values():
                actions.update(role_perms.get(resource, []))
            resource_actions[resource] = sorted(actions)
    else:
        # Get unique resources from tenant permissions
        resources = set()
        for role_perms in TENANT_PERMISSIONS.values():
            resources.update(role_perms.keys())

        # Get all actions per resource
        resource_actions = {}
        for resource in resources:
            actions = set()
            for role_perms in TENANT_PERMISSIONS.values():
                actions.update(role_perms.get(resource, []))
            resource_actions[resource] = sorted(actions)

    return {
        "scope": scope,
        "resources": resource_actions,
    }
