"""
RBAC-003/004: Platform Administration Routes
Generated by Ascend Engineering Team
Application Owner: OW-KAI Technologies, Inc.

Platform-tier routes for OW-AI internal staff using two-pool JWT authentication.

Security Architecture:
- Two-Pool JWT: Platform users authenticate via OWKAI Internal Cognito pool
- Scope Enforcement: Only scope='platform' users can access these routes
- Metadata Only: Returns org metadata ONLY - never customer policies, agents, alerts
- Audit Trail: All actions logged for SOC 2 compliance

Endpoints:
- GET  /platform/orgs          - List all organizations (metadata only)
- GET  /platform/orgs/{id}     - Single organization metadata
- GET  /platform/health        - Platform health status
- POST /platform/orgs/{id}/suspend   - Suspend an organization
- POST /platform/orgs/{id}/activate  - Activate an organization

Security Standards: SOC 2 CC6.1, NIST AC-2, PCI-DSS 7.1

CRITICAL: These routes return METADATA ONLY. Never return:
- Policies, rules, governance configurations
- Agent configurations or secrets
- Alert contents
- Workflow details
- Any tenant business data
"""

import os
import logging
from datetime import datetime, timedelta
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from sqlalchemy import func, text

from database import get_db
from models import Organization, User, AgentAction
from dependencies_platform import get_current_platform_user, require_platform_scope

logger = logging.getLogger("enterprise.platform_routes")

# Feature flag for platform routes
ENABLE_PLATFORM_ROUTES = os.getenv("ENABLE_TWO_POOL_AUTH", "false").lower() == "true"


# =============================================================================
# PYDANTIC SCHEMAS - Metadata Only Responses
# =============================================================================

class OrganizationMetadata(BaseModel):
    """
    Organization metadata (safe for platform admins to view).

    Security: No customer business data, only operational metadata.
    """
    id: int
    name: str
    slug: str
    subscription_tier: str
    subscription_status: str
    created_at: datetime
    user_count: int = 0
    is_suspended: bool = False

    class Config:
        from_attributes = True


class OrganizationDetailMetadata(OrganizationMetadata):
    """Extended organization metadata for single-org view."""
    action_count_30d: int = 0
    action_count_7d: int = 0
    action_count_24h: int = 0
    last_activity: Optional[datetime] = None
    suspended_at: Optional[datetime] = None
    suspended_by: Optional[str] = None
    suspension_reason: Optional[str] = None


class PlatformHealthStatus(BaseModel):
    """Platform-wide health status."""
    status: str  # healthy, degraded, unhealthy
    timestamp: datetime
    database: str  # connected, error
    total_organizations: int
    active_organizations: int
    total_users: int
    uptime_percentage: float = 99.9


class SuspendRequest(BaseModel):
    """Request to suspend an organization."""
    reason: str = Field(..., min_length=10, max_length=500, description="Reason for suspension")


class ActivateRequest(BaseModel):
    """Request to activate a suspended organization."""
    reason: Optional[str] = Field(None, max_length=500, description="Optional note for activation")


class ActionResponse(BaseModel):
    """Standard action response."""
    success: bool
    message: str
    organization_id: int
    action: str
    performed_by: str
    timestamp: datetime


# =============================================================================
# PLATFORM ROUTER
# =============================================================================

router = APIRouter(
    prefix="/platform",
    tags=["Platform Administration (Two-Pool Auth)"]
)


# =============================================================================
# HEALTH ENDPOINT
# =============================================================================

@router.get("/health", response_model=PlatformHealthStatus)
async def get_platform_health(
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_platform_user)
):
    """
    Get platform-wide health status.

    Security:
    - Requires platform scope (OWKAI Internal Cognito pool)
    - Returns aggregate metrics only

    Returns:
        Platform health status with high-level metrics
    """
    require_platform_scope(current_user)

    try:
        # Test database connection
        db.execute(text("SELECT 1"))
        db_status = "connected"
    except Exception as e:
        logger.error(f"Database health check failed: {e}")
        db_status = "error"

    # Get organization counts
    total_orgs = db.query(Organization).count()
    active_orgs = db.query(Organization).filter(
        Organization.subscription_status.in_(['active', 'trial'])
    ).count()

    # Get user count
    total_users = db.query(User).count()

    # Determine overall status
    if db_status == "error":
        overall_status = "unhealthy"
    elif active_orgs == 0:
        overall_status = "degraded"
    else:
        overall_status = "healthy"

    logger.info(f"Platform health check by {current_user.get('email')}: {overall_status}")

    return PlatformHealthStatus(
        status=overall_status,
        timestamp=datetime.utcnow(),
        database=db_status,
        total_organizations=total_orgs,
        active_organizations=active_orgs,
        total_users=total_users,
        uptime_percentage=99.9  # TODO: Integrate with actual monitoring
    )


# =============================================================================
# ORGANIZATION LIST/READ ENDPOINTS
# =============================================================================

@router.get("/orgs", response_model=List[OrganizationMetadata])
async def list_organizations(
    skip: int = 0,
    limit: int = 100,
    status_filter: Optional[str] = None,
    tier_filter: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_platform_user)
):
    """
    List all organizations on the platform (metadata only).

    Security:
    - Requires platform scope (OWKAI Internal Cognito pool)
    - Returns metadata only (no customer business data)
    - Supports pagination and filtering

    Args:
        skip: Pagination offset
        limit: Maximum results (max 100)
        status_filter: Filter by subscription status
        tier_filter: Filter by subscription tier

    Returns:
        List of organization metadata
    """
    require_platform_scope(current_user)

    # Enforce max limit
    limit = min(limit, 100)

    # Build query
    query = db.query(Organization)

    if status_filter:
        query = query.filter(Organization.subscription_status == status_filter)
    if tier_filter:
        query = query.filter(Organization.subscription_tier == tier_filter)

    orgs = query.order_by(Organization.created_at.desc()).offset(skip).limit(limit).all()

    # Enrich with user counts
    results = []
    for org in orgs:
        user_count = db.query(User).filter(User.organization_id == org.id).count()

        # Check if suspended
        is_suspended = org.subscription_status == 'suspended'

        results.append(OrganizationMetadata(
            id=org.id,
            name=org.name,
            slug=org.slug,
            subscription_tier=org.subscription_tier,
            subscription_status=org.subscription_status,
            created_at=org.created_at,
            user_count=user_count,
            is_suspended=is_suspended
        ))

    logger.info(f"Platform user {current_user.get('email')} listed {len(results)} organizations")

    return results


@router.get("/orgs/{org_id}", response_model=OrganizationDetailMetadata)
async def get_organization(
    org_id: int,
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_platform_user)
):
    """
    Get detailed organization metadata.

    Security:
    - Requires platform scope (OWKAI Internal Cognito pool)
    - Returns metadata only (no customer business data)

    Args:
        org_id: Organization ID

    Returns:
        Detailed organization metadata
    """
    require_platform_scope(current_user)

    org = db.query(Organization).filter(Organization.id == org_id).first()
    if not org:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Organization not found"
        )

    # Get user count
    user_count = db.query(User).filter(User.organization_id == org.id).count()

    # Get action counts
    thirty_days_ago = datetime.utcnow() - timedelta(days=30)
    seven_days_ago = datetime.utcnow() - timedelta(days=7)
    one_day_ago = datetime.utcnow() - timedelta(days=1)

    action_count_30d = db.query(AgentAction).filter(
        AgentAction.organization_id == org.id,
        AgentAction.created_at >= thirty_days_ago
    ).count()

    action_count_7d = db.query(AgentAction).filter(
        AgentAction.organization_id == org.id,
        AgentAction.created_at >= seven_days_ago
    ).count()

    action_count_24h = db.query(AgentAction).filter(
        AgentAction.organization_id == org.id,
        AgentAction.created_at >= one_day_ago
    ).count()

    # Get last activity
    last_action = db.query(AgentAction).filter(
        AgentAction.organization_id == org.id
    ).order_by(AgentAction.created_at.desc()).first()

    is_suspended = org.subscription_status == 'suspended'

    logger.info(f"Platform user {current_user.get('email')} viewed org {org_id}")

    return OrganizationDetailMetadata(
        id=org.id,
        name=org.name,
        slug=org.slug,
        subscription_tier=org.subscription_tier,
        subscription_status=org.subscription_status,
        created_at=org.created_at,
        user_count=user_count,
        is_suspended=is_suspended,
        action_count_30d=action_count_30d,
        action_count_7d=action_count_7d,
        action_count_24h=action_count_24h,
        last_activity=last_action.created_at if last_action else None,
        suspended_at=None,  # TODO: Add to Organization model if needed
        suspended_by=None,
        suspension_reason=None
    )


# =============================================================================
# ORGANIZATION MANAGEMENT ENDPOINTS
# =============================================================================

@router.post("/orgs/{org_id}/suspend", response_model=ActionResponse)
async def suspend_organization(
    org_id: int,
    request: SuspendRequest,
    req: Request,
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_platform_user)
):
    """
    Suspend an organization.

    Security:
    - Requires platform scope (OWKAI Internal Cognito pool)
    - Logs action for audit trail
    - Does not delete any data

    Effects:
    - Sets subscription_status to 'suspended'
    - Users cannot log in until reactivated
    - All data preserved for compliance

    Args:
        org_id: Organization ID to suspend
        request: Suspension reason

    Returns:
        Action confirmation
    """
    require_platform_scope(current_user)

    org = db.query(Organization).filter(Organization.id == org_id).first()
    if not org:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Organization not found"
        )

    if org.subscription_status == 'suspended':
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Organization is already suspended"
        )

    # Store previous status for audit
    previous_status = org.subscription_status

    # Suspend the organization
    org.subscription_status = 'suspended'
    db.commit()

    # Log the action
    logger.warning(
        f"PLATFORM ACTION: Organization {org_id} ({org.name}) suspended by "
        f"{current_user.get('email')}. Reason: {request.reason}. "
        f"Previous status: {previous_status}"
    )

    # TODO: Add to audit log table when available
    # audit_log_entry = AuditLog(
    #     action="organization_suspended",
    #     performed_by=current_user.get('email'),
    #     organization_id=org_id,
    #     details={"reason": request.reason, "previous_status": previous_status}
    # )

    return ActionResponse(
        success=True,
        message=f"Organization '{org.name}' has been suspended",
        organization_id=org_id,
        action="suspend",
        performed_by=current_user.get('email'),
        timestamp=datetime.utcnow()
    )


@router.post("/orgs/{org_id}/activate", response_model=ActionResponse)
async def activate_organization(
    org_id: int,
    request: ActivateRequest,
    req: Request,
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_platform_user)
):
    """
    Activate a suspended organization.

    Security:
    - Requires platform scope (OWKAI Internal Cognito pool)
    - Logs action for audit trail

    Effects:
    - Sets subscription_status to 'active'
    - Users can log in again

    Args:
        org_id: Organization ID to activate
        request: Optional activation note

    Returns:
        Action confirmation
    """
    require_platform_scope(current_user)

    org = db.query(Organization).filter(Organization.id == org_id).first()
    if not org:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Organization not found"
        )

    if org.subscription_status != 'suspended':
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Organization is not suspended (current status: {org.subscription_status})"
        )

    # Activate the organization
    org.subscription_status = 'active'
    db.commit()

    # Log the action
    logger.info(
        f"PLATFORM ACTION: Organization {org_id} ({org.name}) activated by "
        f"{current_user.get('email')}. Note: {request.reason or 'None provided'}"
    )

    return ActionResponse(
        success=True,
        message=f"Organization '{org.name}' has been activated",
        organization_id=org_id,
        action="activate",
        performed_by=current_user.get('email'),
        timestamp=datetime.utcnow()
    )
