# RBAC Task 1: Multi-Pool JWT Validator
# SEC-088: Two-Tier Identity Architecture
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# This service validates JWTs from multiple Cognito user pools:
# - Platform Pool (OWKAI Internal) -> scope='platform', org_id=null
# - Tenant Pools (per-organization) -> scope='org', org_id=UUID
#
# Compliance: SOC 2 CC6.1, NIST IA-2, PCI-DSS 8.2
"""
Multi-Pool JWT Validator for SEC-088 Two-Tier Identity.

This service provides:
- Validation of JWTs from OWKAI Internal (platform) pool
- Validation of JWTs from per-organization tenant pools
- JWKS caching with 60-minute TTL per pool
- Scope determination based on token issuer
- Fail-secure behavior on all errors

Architecture:
    Platform Pool (OWKAI Internal)
    - Users: Ascend staff (Super Admin, Support, Billing)
    - scope: 'platform'
    - org_id: null (enforced)
    - Access: /platform/* routes only

    Tenant Pools (per-organization)
    - Users: Customer users (Owner, Admin, Approver, Operator, Viewer)
    - scope: 'org'
    - org_id: UUID (required)
    - Access: /api/* routes only

Usage:
    from services.multi_pool_jwt_validator import MultiPoolJWTValidator

    validator = MultiPoolJWTValidator(db)
    claims = await validator.validate_token(token)
    # claims.scope = 'platform' or 'org'
    # claims.org_id = None or UUID string
"""

import os
import jwt
import time
import httpx
import logging
import hashlib
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from threading import Lock
from uuid import UUID

from jwt import PyJWKClient
from jwt.exceptions import PyJWTError

logger = logging.getLogger(__name__)


# =============================================================================
# CONFIGURATION
# =============================================================================

# AWS Region for Cognito
AWS_REGION = os.getenv("AWS_REGION", "us-east-2")

# Platform Pool Configuration (OWKAI Internal)
# This is the Ascend staff pool - hardcoded for security
PLATFORM_POOL_ID = os.getenv("COGNITO_PLATFORM_POOL_ID", "us-east-2_aB0BefD8f")
PLATFORM_POOL_CLIENT_ID = os.getenv("COGNITO_PLATFORM_CLIENT_ID")

# JWKS Cache TTL (60 minutes per spec)
JWKS_CACHE_TTL_SECONDS = int(os.getenv("JWKS_CACHE_TTL_SECONDS", "3600"))

# Token validation settings
TOKEN_LEEWAY_SECONDS = 30  # Clock skew tolerance
REQUIRED_CLAIMS = ["sub", "iss", "aud", "exp", "iat", "token_use"]


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass(frozen=True)
class TokenClaims:
    """
    Immutable token claims container.

    Represents validated claims from a Cognito JWT with
    scope and organization context for two-tier identity.
    """
    sub: str                          # Cognito user ID (subject)
    iss: str                          # Issuer (Cognito pool URL)
    aud: str                          # Audience (app client ID)
    exp: int                          # Expiration timestamp
    iat: int                          # Issued at timestamp
    token_use: str                    # 'access' or 'id'
    scope: str                        # 'platform' or 'org'
    org_id: Optional[str]             # Organization UUID (null for platform)
    pool_id: str                      # Cognito pool ID that issued token
    email: Optional[str] = None       # User email (from ID token)
    cognito_groups: List[str] = field(default_factory=list)  # Cognito groups
    custom_claims: Dict[str, Any] = field(default_factory=dict)

    @property
    def user_id(self) -> str:
        """Alias for sub claim."""
        return self.sub

    @property
    def is_platform_user(self) -> bool:
        """Check if this is a platform (Ascend staff) user."""
        return self.scope == "platform"

    @property
    def is_tenant_user(self) -> bool:
        """Check if this is a tenant (customer) user."""
        return self.scope == "org"

    @property
    def is_expired(self) -> bool:
        """Check if token has expired."""
        return time.time() > self.exp

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "sub": self.sub,
            "user_id": self.user_id,
            "iss": self.iss,
            "aud": self.aud,
            "exp": self.exp,
            "iat": self.iat,
            "token_use": self.token_use,
            "scope": self.scope,
            "org_id": self.org_id,
            "pool_id": self.pool_id,
            "email": self.email,
            "cognito_groups": self.cognito_groups,
            "is_platform_user": self.is_platform_user,
            "is_tenant_user": self.is_tenant_user,
        }


@dataclass
class JWKSCacheEntry:
    """JWKS cache entry with TTL tracking."""
    jwks_client: PyJWKClient
    cached_at: float
    pool_id: str

    @property
    def is_expired(self) -> bool:
        """Check if cache entry has expired."""
        return (time.time() - self.cached_at) > JWKS_CACHE_TTL_SECONDS

    @property
    def age_seconds(self) -> float:
        """Get age of cache entry in seconds."""
        return time.time() - self.cached_at


# =============================================================================
# EXCEPTIONS
# =============================================================================

class MultiPoolJWTError(Exception):
    """Base exception for multi-pool JWT validation errors."""
    pass


class UnknownPoolError(MultiPoolJWTError):
    """Token issued by unknown Cognito pool."""
    def __init__(self, issuer: str):
        self.issuer = issuer
        super().__init__(f"Token issued by unknown pool: {issuer}")


class InvalidTokenError(MultiPoolJWTError):
    """Token is invalid or malformed."""
    pass


class TokenExpiredError(MultiPoolJWTError):
    """Token has expired."""
    def __init__(self, exp: int):
        self.exp = exp
        super().__init__(f"Token expired at {datetime.fromtimestamp(exp).isoformat()}")


class ScopeViolationError(MultiPoolJWTError):
    """Token scope does not match expected scope."""
    def __init__(self, expected: str, actual: str):
        self.expected = expected
        self.actual = actual
        super().__init__(f"Expected scope '{expected}', got '{actual}'")


class OrganizationMismatchError(MultiPoolJWTError):
    """Token organization does not match expected organization."""
    def __init__(self, expected: str, actual: str):
        self.expected = expected
        self.actual = actual
        super().__init__(f"Expected org_id '{expected}', got '{actual}'")


# =============================================================================
# MULTI-POOL JWT VALIDATOR
# =============================================================================

class MultiPoolJWTValidator:
    """
    Validates JWTs from multiple Cognito user pools.

    Supports two-tier identity architecture:
    - Platform tier: OWKAI Internal pool for Ascend staff
    - Tenant tier: Per-organization pools for customers

    Features:
    - JWKS caching with configurable TTL (default 60 min)
    - Automatic scope determination from issuer
    - Organization lookup from database for tenant pools
    - Fail-secure on all validation errors
    - Comprehensive audit logging
    """

    def __init__(self, db_session=None):
        """
        Initialize validator.

        Args:
            db_session: SQLAlchemy session for organization lookups.
                       Required for tenant pool validation.
        """
        self._db = db_session
        self._jwks_cache: Dict[str, JWKSCacheEntry] = {}
        self._cache_lock = Lock()
        self._known_tenant_pools: Dict[str, str] = {}  # pool_id -> org_id mapping

        logger.info(
            f"SEC-088: MultiPoolJWTValidator initialized | "
            f"platform_pool={PLATFORM_POOL_ID} | "
            f"region={AWS_REGION} | "
            f"jwks_cache_ttl={JWKS_CACHE_TTL_SECONDS}s"
        )

    # =========================================================================
    # PUBLIC API
    # =========================================================================

    async def validate_token(
        self,
        token: str,
        expected_scope: Optional[str] = None,
        expected_org_id: Optional[str] = None,
    ) -> TokenClaims:
        """
        Validate a JWT token and return claims.

        This is the primary validation method that:
        1. Decodes token header to identify issuing pool
        2. Determines scope (platform vs org) from issuer
        3. Fetches/caches JWKS for the pool
        4. Validates signature and claims
        5. Returns immutable TokenClaims

        Args:
            token: JWT token string (access or id token)
            expected_scope: If provided, validates scope matches
            expected_org_id: If provided, validates org_id matches

        Returns:
            TokenClaims with validated claims and scope

        Raises:
            InvalidTokenError: Token is malformed
            UnknownPoolError: Token from unknown pool
            TokenExpiredError: Token has expired
            ScopeViolationError: Scope mismatch (if expected_scope provided)
            OrganizationMismatchError: Org mismatch (if expected_org_id provided)
            MultiPoolJWTError: Other validation failures
        """
        try:
            # Step 1: Decode header (no verification) to get issuer
            unverified = self._decode_unverified(token)
            issuer = unverified.get("iss", "")

            # Step 2: Identify pool and scope from issuer
            pool_id, scope, org_id = await self._identify_pool(issuer)

            logger.debug(
                f"SEC-088: Token pool identified | "
                f"pool_id={pool_id} | "
                f"scope={scope} | "
                f"org_id={org_id}"
            )

            # Step 3: Get JWKS client for this pool
            jwks_client = self._get_jwks_client(pool_id)

            # Step 4: Get signing key from JWKS
            signing_key = jwks_client.get_signing_key_from_jwt(token)

            # Step 5: Verify signature and decode claims
            claims = jwt.decode(
                token,
                signing_key.key,
                algorithms=["RS256"],
                options={
                    "verify_signature": True,
                    "verify_exp": True,
                    "verify_iat": True,
                    "verify_aud": False,  # Cognito uses client_id, not standard aud
                    "require": ["sub", "iss", "exp", "iat", "token_use"],
                },
                leeway=TOKEN_LEEWAY_SECONDS,
            )

            # Step 6: Extract additional claims
            email = claims.get("email")
            cognito_groups = claims.get("cognito:groups", [])
            token_use = claims.get("token_use", "access")
            aud = claims.get("aud", claims.get("client_id", ""))

            # Step 7: Build immutable TokenClaims
            token_claims = TokenClaims(
                sub=claims["sub"],
                iss=claims["iss"],
                aud=aud,
                exp=claims["exp"],
                iat=claims["iat"],
                token_use=token_use,
                scope=scope,
                org_id=org_id,
                pool_id=pool_id,
                email=email,
                cognito_groups=cognito_groups,
                custom_claims={
                    k: v for k, v in claims.items()
                    if k.startswith("custom:")
                },
            )

            # Step 8: Validate scope if expected
            if expected_scope and token_claims.scope != expected_scope:
                logger.warning(
                    f"SEC-088: Scope violation | "
                    f"expected={expected_scope} | "
                    f"actual={token_claims.scope} | "
                    f"user_id={token_claims.sub}"
                )
                raise ScopeViolationError(expected_scope, token_claims.scope)

            # Step 9: Validate org_id if expected
            if expected_org_id and token_claims.org_id != expected_org_id:
                logger.warning(
                    f"SEC-088: Organization mismatch | "
                    f"expected={expected_org_id} | "
                    f"actual={token_claims.org_id} | "
                    f"user_id={token_claims.sub}"
                )
                raise OrganizationMismatchError(expected_org_id, token_claims.org_id)

            logger.info(
                f"SEC-088: Token validated | "
                f"user_id={token_claims.sub} | "
                f"scope={token_claims.scope} | "
                f"org_id={token_claims.org_id} | "
                f"pool_id={pool_id}"
            )

            return token_claims

        except jwt.ExpiredSignatureError:
            exp = self._decode_unverified(token).get("exp", 0)
            logger.warning(f"SEC-088: Token expired | exp={exp}")
            raise TokenExpiredError(exp)

        except jwt.InvalidSignatureError:
            logger.warning("SEC-088: Invalid token signature")
            raise InvalidTokenError("Token signature verification failed")

        except jwt.DecodeError as e:
            logger.warning(f"SEC-088: Token decode error | error={e}")
            raise InvalidTokenError(f"Token decode failed: {e}")

        except (ScopeViolationError, OrganizationMismatchError, UnknownPoolError):
            # Re-raise our custom exceptions
            raise

        except Exception as e:
            # FAIL SECURE: Any unexpected error results in rejection
            logger.error(f"SEC-088: Unexpected validation error | error={e}")
            raise InvalidTokenError(f"Token validation failed: {e}")

    def validate_platform_token(self, token: str) -> TokenClaims:
        """
        Validate a token and require platform scope.

        Convenience method for /platform/* routes.

        Args:
            token: JWT token string

        Returns:
            TokenClaims with scope='platform'

        Raises:
            ScopeViolationError: If token is not platform scope
        """
        import asyncio
        return asyncio.get_event_loop().run_until_complete(
            self.validate_token(token, expected_scope="platform")
        )

    def validate_tenant_token(
        self,
        token: str,
        expected_org_id: Optional[str] = None,
    ) -> TokenClaims:
        """
        Validate a token and require org scope.

        Convenience method for /api/* routes.

        Args:
            token: JWT token string
            expected_org_id: If provided, also validates org_id

        Returns:
            TokenClaims with scope='org'

        Raises:
            ScopeViolationError: If token is not org scope
            OrganizationMismatchError: If org_id doesn't match expected
        """
        import asyncio
        return asyncio.get_event_loop().run_until_complete(
            self.validate_token(
                token,
                expected_scope="org",
                expected_org_id=expected_org_id,
            )
        )

    # =========================================================================
    # POOL IDENTIFICATION
    # =========================================================================

    async def _identify_pool(self, issuer: str) -> Tuple[str, str, Optional[str]]:
        """
        Identify Cognito pool and scope from issuer URL.

        Args:
            issuer: Token issuer claim (Cognito pool URL)

        Returns:
            Tuple of (pool_id, scope, org_id)
            - Platform: (pool_id, 'platform', None)
            - Tenant: (pool_id, 'org', org_id)

        Raises:
            UnknownPoolError: If pool cannot be identified
        """
        # Parse pool ID from issuer URL
        # Format: https://cognito-idp.{region}.amazonaws.com/{pool_id}
        if not issuer.startswith("https://cognito-idp."):
            raise UnknownPoolError(issuer)

        try:
            pool_id = issuer.split("/")[-1]
        except (IndexError, AttributeError):
            raise UnknownPoolError(issuer)

        # Check if this is the platform pool
        if pool_id == PLATFORM_POOL_ID:
            logger.debug(f"SEC-088: Platform pool identified | pool_id={pool_id}")
            return (pool_id, "platform", None)

        # Check cache for known tenant pools
        if pool_id in self._known_tenant_pools:
            org_id = self._known_tenant_pools[pool_id]
            logger.debug(
                f"SEC-088: Tenant pool identified (cached) | "
                f"pool_id={pool_id} | "
                f"org_id={org_id}"
            )
            return (pool_id, "org", org_id)

        # Look up pool in database
        org_id = await self._lookup_pool_organization(pool_id)
        if org_id:
            # Cache the mapping
            self._known_tenant_pools[pool_id] = org_id
            logger.debug(
                f"SEC-088: Tenant pool identified (db lookup) | "
                f"pool_id={pool_id} | "
                f"org_id={org_id}"
            )
            return (pool_id, "org", org_id)

        # Unknown pool - reject
        logger.warning(f"SEC-088: Unknown pool | pool_id={pool_id} | issuer={issuer}")
        raise UnknownPoolError(issuer)

    async def _lookup_pool_organization(self, pool_id: str) -> Optional[str]:
        """
        Look up organization by Cognito pool ID.

        Args:
            pool_id: Cognito user pool ID

        Returns:
            Organization ID (as string) or None if not found
        """
        if not self._db:
            logger.warning(
                "SEC-088: Database session not available for pool lookup | "
                f"pool_id={pool_id}"
            )
            return None

        try:
            from models import Organization

            org = self._db.query(Organization).filter(
                Organization.cognito_user_pool_id == pool_id,
                Organization.cognito_pool_status == "active",
            ).first()

            if org:
                return str(org.id)

            return None

        except Exception as e:
            logger.error(
                f"SEC-088: Failed to lookup organization | "
                f"pool_id={pool_id} | "
                f"error={e}"
            )
            return None

    # =========================================================================
    # JWKS CACHING
    # =========================================================================

    def _get_jwks_client(self, pool_id: str) -> PyJWKClient:
        """
        Get JWKS client for a Cognito pool with caching.

        Implements 60-minute TTL cache per pool.

        Args:
            pool_id: Cognito user pool ID

        Returns:
            PyJWKClient configured for the pool
        """
        with self._cache_lock:
            # Check cache
            if pool_id in self._jwks_cache:
                entry = self._jwks_cache[pool_id]
                if not entry.is_expired:
                    logger.debug(
                        f"SEC-088: JWKS cache hit | "
                        f"pool_id={pool_id} | "
                        f"age={entry.age_seconds:.1f}s"
                    )
                    return entry.jwks_client
                else:
                    logger.debug(
                        f"SEC-088: JWKS cache expired | "
                        f"pool_id={pool_id} | "
                        f"age={entry.age_seconds:.1f}s"
                    )

            # Create new JWKS client
            jwks_url = self._build_jwks_url(pool_id)
            logger.info(f"SEC-088: Fetching JWKS | pool_id={pool_id} | url={jwks_url}")

            jwks_client = PyJWKClient(
                jwks_url,
                cache_jwk_set=True,
                lifespan=JWKS_CACHE_TTL_SECONDS,
            )

            # Cache the client
            self._jwks_cache[pool_id] = JWKSCacheEntry(
                jwks_client=jwks_client,
                cached_at=time.time(),
                pool_id=pool_id,
            )

            logger.info(
                f"SEC-088: JWKS cached | "
                f"pool_id={pool_id} | "
                f"ttl={JWKS_CACHE_TTL_SECONDS}s"
            )

            return jwks_client

    def _build_jwks_url(self, pool_id: str) -> str:
        """Build JWKS URL for a Cognito pool."""
        return (
            f"https://cognito-idp.{AWS_REGION}.amazonaws.com/"
            f"{pool_id}/.well-known/jwks.json"
        )

    def invalidate_cache(self, pool_id: Optional[str] = None) -> int:
        """
        Invalidate JWKS cache.

        Args:
            pool_id: If provided, only invalidate this pool.
                    If None, invalidate all pools.

        Returns:
            Number of cache entries invalidated
        """
        with self._cache_lock:
            if pool_id:
                if pool_id in self._jwks_cache:
                    del self._jwks_cache[pool_id]
                    logger.info(f"SEC-088: JWKS cache invalidated | pool_id={pool_id}")
                    return 1
                return 0
            else:
                count = len(self._jwks_cache)
                self._jwks_cache.clear()
                logger.info(f"SEC-088: JWKS cache cleared | entries={count}")
                return count

    def get_cache_stats(self) -> Dict[str, Any]:
        """Get JWKS cache statistics."""
        with self._cache_lock:
            entries = []
            for pool_id, entry in self._jwks_cache.items():
                entries.append({
                    "pool_id": pool_id,
                    "cached_at": datetime.fromtimestamp(entry.cached_at).isoformat(),
                    "age_seconds": entry.age_seconds,
                    "is_expired": entry.is_expired,
                })

            return {
                "cache_entries": len(self._jwks_cache),
                "ttl_seconds": JWKS_CACHE_TTL_SECONDS,
                "entries": entries,
            }

    # =========================================================================
    # UTILITIES
    # =========================================================================

    def _decode_unverified(self, token: str) -> Dict[str, Any]:
        """
        Decode token without verification.

        Used only to extract issuer for pool identification.
        NEVER use for authorization decisions.
        """
        return jwt.decode(token, options={"verify_signature": False})

    def register_tenant_pool(self, pool_id: str, org_id: str) -> None:
        """
        Register a tenant pool mapping.

        Used during organization onboarding when pool is created.

        Args:
            pool_id: Cognito user pool ID
            org_id: Organization ID
        """
        self._known_tenant_pools[pool_id] = org_id
        logger.info(
            f"SEC-088: Tenant pool registered | "
            f"pool_id={pool_id} | "
            f"org_id={org_id}"
        )

    def unregister_tenant_pool(self, pool_id: str) -> bool:
        """
        Unregister a tenant pool mapping.

        Used when organization is suspended or deleted.

        Args:
            pool_id: Cognito user pool ID

        Returns:
            True if pool was registered, False otherwise
        """
        if pool_id in self._known_tenant_pools:
            del self._known_tenant_pools[pool_id]
            self.invalidate_cache(pool_id)
            logger.info(f"SEC-088: Tenant pool unregistered | pool_id={pool_id}")
            return True
        return False


# =============================================================================
# SINGLETON & FACTORY
# =============================================================================

_validator_instance: Optional[MultiPoolJWTValidator] = None
_validator_lock = Lock()


def get_multi_pool_validator(db_session=None) -> MultiPoolJWTValidator:
    """
    Get singleton MultiPoolJWTValidator instance.

    Args:
        db_session: SQLAlchemy session (required for first initialization)

    Returns:
        MultiPoolJWTValidator instance
    """
    global _validator_instance

    with _validator_lock:
        if _validator_instance is None:
            _validator_instance = MultiPoolJWTValidator(db_session)
        elif db_session and _validator_instance._db is None:
            # Update DB session if not set
            _validator_instance._db = db_session

        return _validator_instance


def create_validator(db_session=None) -> MultiPoolJWTValidator:
    """
    Create a new MultiPoolJWTValidator instance.

    Use this for testing or when you need a fresh validator.

    Args:
        db_session: SQLAlchemy session

    Returns:
        New MultiPoolJWTValidator instance
    """
    return MultiPoolJWTValidator(db_session)
