# SEC-081: Unified Password Service (Pepper + Argon2id)
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# This service implements defense-in-depth password hashing per SEC-081:
# 1. HMAC-SHA256 with pepper (defense against DB compromise)
# 2. Argon2id memory-hard hashing (OWASP 2024 recommended)
#
# Compliance: NIST SP 800-63B, OWASP ASVS 2.4.4, PCI-DSS 8.2
"""
Unified Password Service for SEC-081.

Implements two-layer password protection:
    Layer 1: HMAC-SHA256 with pepper (stored in AWS Secrets Manager)
    Layer 2: Argon2id memory-hard KDF (parameters per OWASP 2024)

Defense-in-Depth:
    - If database is compromised: Attacker has hashes but not pepper
    - If secrets manager is compromised: Attacker has pepper but not hashes
    - Both are required to crack passwords

Usage:
    from services.password_service import PasswordService

    # Initialize
    password_service = PasswordService()

    # Hash password
    hashed = password_service.hash("user_password")

    # Verify password
    if password_service.verify("user_password", hashed):
        # Password is correct
        pass

    # Check if hash needs upgrade (bcrypt → Argon2id)
    if password_service.needs_rehash(hashed):
        new_hash = password_service.hash("user_password")
"""

import os
import hmac
import hashlib
import logging
import re
from typing import Optional, Tuple
from base64 import b64encode, b64decode

from .unified_auth.constants import (
    ARGON2_MEMORY_COST,
    ARGON2_TIME_COST,
    ARGON2_PARALLELISM,
    ARGON2_HASH_LENGTH,
    ARGON2_SALT_LENGTH,
    PEPPER_SECRET_NAME,
    PEPPER_ENV_VAR,
    BCRYPT_HASH_PREFIX,
    BCRYPT_HASH_PREFIX_ALT,
)
from .unified_auth.exceptions import (
    PasswordHashingError,
    PepperNotConfiguredError,
    PasswordVerificationError,
)

logger = logging.getLogger(__name__)

# Lazy import argon2 to allow graceful fallback
try:
    from argon2 import PasswordHasher, Type
    from argon2.exceptions import (
        VerifyMismatchError,
        VerificationError,
        InvalidHash,
    )
    ARGON2_AVAILABLE = True
except ImportError:
    ARGON2_AVAILABLE = False
    logger.warning(
        "SEC-081: argon2-cffi not installed. "
        "Install with: pip install argon2-cffi"
    )

# Lazy import bcrypt for migration support
try:
    import bcrypt
    BCRYPT_AVAILABLE = True
except ImportError:
    BCRYPT_AVAILABLE = False


class PasswordService:
    """
    Unified Password Service with Pepper + Argon2id.

    Provides defense-in-depth password hashing with automatic
    migration from bcrypt to Argon2id.

    Attributes:
        pepper: HMAC pepper from AWS Secrets Manager
        argon2_hasher: Configured Argon2id hasher
        environment: Current environment (production/development)
    """

    # Hash format identifier
    ARGON2_PREFIX = "$argon2id$"

    def __init__(
        self,
        pepper: Optional[str] = None,
        environment: Optional[str] = None,
    ):
        """
        Initialize PasswordService.

        Args:
            pepper: HMAC pepper (loaded from secrets if not provided)
            environment: Environment name (for production enforcement)

        Raises:
            PepperNotConfiguredError: If pepper missing in production
        """
        self.environment = environment or os.environ.get("ENVIRONMENT", "development")

        # Load pepper
        self._pepper = pepper or self._load_pepper()

        # Initialize Argon2id hasher with OWASP 2024 parameters
        if ARGON2_AVAILABLE:
            self._hasher = PasswordHasher(
                time_cost=ARGON2_TIME_COST,
                memory_cost=ARGON2_MEMORY_COST,
                parallelism=ARGON2_PARALLELISM,
                hash_len=ARGON2_HASH_LENGTH,
                salt_len=ARGON2_SALT_LENGTH,
                type=Type.ID,  # Argon2id (recommended)
            )
        else:
            self._hasher = None

        # Log initialization
        pepper_status = "configured" if self._pepper else "NOT CONFIGURED"
        logger.info(
            f"SEC-081: PasswordService initialized | "
            f"argon2={ARGON2_AVAILABLE} | "
            f"bcrypt_migration={BCRYPT_AVAILABLE} | "
            f"pepper={pepper_status} | "
            f"memory_cost={ARGON2_MEMORY_COST}KB"
        )

    def _load_pepper(self) -> Optional[str]:
        """
        Load password pepper from AWS Secrets Manager or environment.

        Order:
        1. AWS Secrets Manager (production)
        2. Environment variable (fallback)
        3. None (development only)

        Returns:
            Pepper string or None

        Raises:
            PepperNotConfiguredError: If pepper missing in production
        """
        # Try AWS Secrets Manager
        pepper = self._get_from_secrets_manager(PEPPER_SECRET_NAME)
        if pepper:
            logger.debug("SEC-081: Pepper loaded from AWS Secrets Manager")
            return pepper

        # Try environment variable
        pepper = os.environ.get(PEPPER_ENV_VAR)
        if pepper:
            logger.debug("SEC-081: Pepper loaded from environment variable")
            return pepper

        # Production requires pepper
        if self.environment.lower() == "production":
            raise PepperNotConfiguredError(
                f"SEC-081 CRITICAL: Password pepper not configured. "
                f"Set {PEPPER_ENV_VAR} or create {PEPPER_SECRET_NAME} in Secrets Manager."
            )

        # Development: Warning but continue
        logger.warning(
            "SEC-081: Password pepper not configured (development mode). "
            "This is NOT safe for production!"
        )
        return None

    def _get_from_secrets_manager(self, secret_name: str) -> Optional[str]:
        """Get secret from AWS Secrets Manager."""
        try:
            import boto3
            from botocore.exceptions import ClientError

            client = boto3.client(
                "secretsmanager",
                region_name=os.environ.get("AWS_REGION", "us-east-2")
            )

            response = client.get_secret_value(SecretId=secret_name)
            return response.get("SecretString")

        except Exception as e:
            logger.debug(f"SEC-081: Could not load from Secrets Manager: {e}")
            return None

    # =========================================================================
    # PEPPER APPLICATION
    # =========================================================================

    def _apply_pepper(self, password: str) -> str:
        """
        Apply HMAC-SHA256 pepper to password.

        This is Layer 1 of defense-in-depth. The peppered password
        is then passed to Argon2id for final hashing.

        Args:
            password: Plain text password

        Returns:
            HMAC-SHA256(password, pepper) as hex string

        Security Note:
            If pepper is not configured (development only), returns
            password unchanged. This allows testing without pepper
            but is blocked in production by _load_pepper().
        """
        if not self._pepper:
            logger.debug("SEC-081: No pepper configured, using raw password")
            return password

        # HMAC-SHA256 with pepper as key
        peppered = hmac.new(
            key=self._pepper.encode("utf-8"),
            msg=password.encode("utf-8"),
            digestmod=hashlib.sha256
        ).hexdigest()

        return peppered

    # =========================================================================
    # PASSWORD HASHING
    # =========================================================================

    def hash(self, password: str) -> str:
        """
        Hash password with pepper + Argon2id.

        Process:
        1. Apply HMAC-SHA256 pepper (defense-in-depth)
        2. Hash with Argon2id (memory-hard KDF)

        Args:
            password: Plain text password

        Returns:
            Argon2id hash string

        Raises:
            PasswordHashingError: If hashing fails
        """
        if not ARGON2_AVAILABLE:
            raise PasswordHashingError(
                "SEC-081: argon2-cffi not installed. "
                "Cannot hash passwords without Argon2id."
            )

        try:
            # Layer 1: Apply pepper
            peppered = self._apply_pepper(password)

            # Layer 2: Argon2id hash
            hashed = self._hasher.hash(peppered)

            logger.debug("SEC-081: Password hashed successfully with Argon2id")
            return hashed

        except Exception as e:
            logger.error(f"SEC-081: Password hashing failed: {e}")
            raise PasswordHashingError(f"Failed to hash password: {e}")

    # =========================================================================
    # PASSWORD VERIFICATION
    # =========================================================================

    def verify(self, password: str, hash_string: str) -> bool:
        """
        Verify password against stored hash.

        Supports both Argon2id (new) and bcrypt (legacy) hashes
        for seamless migration.

        Args:
            password: Plain text password to verify
            hash_string: Stored hash to verify against

        Returns:
            True if password matches, False otherwise
        """
        try:
            # Detect hash type
            if self._is_argon2_hash(hash_string):
                return self._verify_argon2(password, hash_string)
            elif self._is_bcrypt_hash(hash_string):
                return self._verify_bcrypt(password, hash_string)
            else:
                logger.warning(f"SEC-081: Unknown hash format")
                return False

        except Exception as e:
            logger.error(f"SEC-081: Password verification error: {e}")
            return False

    def _verify_argon2(self, password: str, hash_string: str) -> bool:
        """Verify password against Argon2id hash."""
        if not ARGON2_AVAILABLE:
            raise PasswordHashingError("argon2-cffi not available")

        try:
            # Apply pepper before verification
            peppered = self._apply_pepper(password)

            # Verify with Argon2id
            self._hasher.verify(hash_string, peppered)
            return True

        except VerifyMismatchError:
            return False
        except (VerificationError, InvalidHash) as e:
            logger.warning(f"SEC-081: Argon2 verification error: {e}")
            return False

    def _verify_bcrypt(self, password: str, hash_string: str) -> bool:
        """
        Verify password against legacy bcrypt hash.

        Supports two bcrypt formats from existing codebase:
        1. Direct bcrypt (password → bcrypt)
        2. SHA-256 + bcrypt (password → SHA-256 → bcrypt)

        Args:
            password: Plain text password
            hash_string: Bcrypt hash string

        Returns:
            True if password matches, False otherwise
        """
        if not BCRYPT_AVAILABLE:
            logger.warning("SEC-081: bcrypt not available for legacy hash")
            return False

        try:
            hash_bytes = hash_string.encode("utf-8")

            # Try SHA-256 + bcrypt (auth_utils.py pattern)
            sha_digest = hashlib.sha256(password.encode("utf-8")).hexdigest()
            if bcrypt.checkpw(sha_digest.encode("utf-8"), hash_bytes):
                logger.info(
                    "SEC-081: Legacy bcrypt (SHA-256+bcrypt) verified. "
                    "Consider rehashing with Argon2id."
                )
                return True

            # Try direct bcrypt (core/security.py pattern)
            if bcrypt.checkpw(password.encode("utf-8"), hash_bytes):
                logger.info(
                    "SEC-081: Legacy bcrypt (direct) verified. "
                    "Consider rehashing with Argon2id."
                )
                return True

            return False

        except Exception as e:
            logger.warning(f"SEC-081: bcrypt verification error: {e}")
            return False

    # =========================================================================
    # HASH TYPE DETECTION
    # =========================================================================

    def _is_argon2_hash(self, hash_string: str) -> bool:
        """Check if hash is Argon2id format."""
        return hash_string.startswith(self.ARGON2_PREFIX)

    def _is_bcrypt_hash(self, hash_string: str) -> bool:
        """Check if hash is bcrypt format."""
        return (
            hash_string.startswith(BCRYPT_HASH_PREFIX) or
            hash_string.startswith(BCRYPT_HASH_PREFIX_ALT)
        )

    # =========================================================================
    # HASH MIGRATION
    # =========================================================================

    def needs_rehash(self, hash_string: str) -> bool:
        """
        Check if hash needs upgrade to Argon2id.

        Returns True if:
        - Hash is bcrypt format (needs migration)
        - Hash uses outdated Argon2 parameters

        Args:
            hash_string: Stored hash to check

        Returns:
            True if rehash is recommended
        """
        # Legacy bcrypt hashes need migration
        if self._is_bcrypt_hash(hash_string):
            return True

        # Check if Argon2 parameters need update
        if self._is_argon2_hash(hash_string) and ARGON2_AVAILABLE:
            try:
                return self._hasher.check_needs_rehash(hash_string)
            except Exception:  # nosec B110 - Intentional silent catch for hash check
                return False  # If check fails, assume no rehash needed

        return False

    def verify_and_upgrade(
        self,
        password: str,
        hash_string: str
    ) -> Tuple[bool, Optional[str]]:
        """
        Verify password and upgrade hash if needed.

        This method combines verification with automatic migration.
        Use in login flow to transparently upgrade legacy hashes.

        Args:
            password: Plain text password
            hash_string: Stored hash

        Returns:
            Tuple of (is_valid, new_hash_or_none)
            - If valid and needs upgrade: (True, new_argon2_hash)
            - If valid and no upgrade needed: (True, None)
            - If invalid: (False, None)

        Example:
            is_valid, new_hash = password_service.verify_and_upgrade(
                password, stored_hash
            )
            if is_valid:
                if new_hash:
                    # Update database with new hash
                    user.password_hash = new_hash
                # Allow login
            else:
                # Reject login
        """
        # Verify password
        is_valid = self.verify(password, hash_string)

        if not is_valid:
            return (False, None)

        # Check if upgrade needed
        if self.needs_rehash(hash_string):
            try:
                new_hash = self.hash(password)
                logger.info(
                    "SEC-081: Password hash upgraded from "
                    f"{'bcrypt' if self._is_bcrypt_hash(hash_string) else 'old Argon2'} "
                    "to Argon2id"
                )
                return (True, new_hash)
            except Exception as e:
                logger.warning(f"SEC-081: Hash upgrade failed: {e}")
                # Still valid, just not upgraded
                return (True, None)

        return (True, None)

    # =========================================================================
    # UTILITY METHODS
    # =========================================================================

    def get_hash_info(self, hash_string: str) -> dict:
        """
        Get information about a password hash.

        Useful for debugging and migration tracking.

        Args:
            hash_string: Hash to analyze

        Returns:
            Dictionary with hash information
        """
        if self._is_argon2_hash(hash_string):
            # Parse Argon2 parameters from hash
            # Format: $argon2id$v=19$m=65536,t=3,p=4$salt$hash
            match = re.match(
                r'\$argon2id\$v=(\d+)\$m=(\d+),t=(\d+),p=(\d+)\$',
                hash_string
            )
            if match:
                return {
                    "type": "argon2id",
                    "version": int(match.group(1)),
                    "memory_cost": int(match.group(2)),
                    "time_cost": int(match.group(3)),
                    "parallelism": int(match.group(4)),
                    "needs_rehash": self.needs_rehash(hash_string),
                }
            return {"type": "argon2id", "needs_rehash": self.needs_rehash(hash_string)}

        elif self._is_bcrypt_hash(hash_string):
            # Parse bcrypt cost factor
            match = re.match(r'\$2[ab]\$(\d+)\$', hash_string)
            cost = int(match.group(1)) if match else None
            return {
                "type": "bcrypt",
                "cost_factor": cost,
                "needs_rehash": True,  # All bcrypt needs migration
            }

        return {"type": "unknown", "needs_rehash": True}


# Singleton instance for dependency injection
_password_service_instance: Optional[PasswordService] = None


def get_password_service() -> PasswordService:
    """
    Get singleton PasswordService instance.

    Returns:
        PasswordService instance
    """
    global _password_service_instance
    if _password_service_instance is None:
        _password_service_instance = PasswordService()
    return _password_service_instance
