# SEC-081: Token Revocation Service
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# Provides token revocation (blacklist) functionality for logout,
# session termination, and security events.
#
# Compliance: SOC 2 CC6.2, NIST AC-12, PCI-DSS 8.1.8
"""
Token Revocation Service for SEC-081.

Implements token blacklisting with dual backend support:
- Redis: Production (distributed, persistent)
- In-Memory: Development (single-process, ephemeral)

Usage:
    from services.revocation_service import RevocationService

    # Initialize with Redis (production)
    revocation = RevocationService(redis_url="redis://localhost:6379")

    # Or use in-memory (development)
    revocation = RevocationService(use_memory=True)

    # Revoke a token
    revocation.revoke(jti="tok_abc123", expires_at=1733348400)

    # Check if revoked
    if revocation.is_revoked("tok_abc123"):
        raise TokenRevokedError()

    # Revoke entire session
    revocation.revoke_session("sess_xyz789")
"""

import os
import time
import logging
from typing import Optional, Set, Dict
from datetime import datetime
from threading import Lock
from collections import OrderedDict

from .unified_auth.constants import (
    REVOCATION_KEY_PREFIX,
    REVOCATION_TTL_PADDING_SECONDS,
    REVOCATION_CACHE_MAX_SIZE,
)
from .unified_auth.exceptions import RevocationServiceError

logger = logging.getLogger(__name__)

# Lazy import Redis
try:
    import redis
    REDIS_AVAILABLE = True
except ImportError:
    REDIS_AVAILABLE = False
    logger.debug("SEC-081: redis not installed, using in-memory backend")


class InMemoryRevocationBackend:
    """
    In-memory token revocation backend for development.

    Features:
    - Thread-safe operations
    - Automatic TTL-based cleanup
    - LRU eviction when max size reached

    WARNING: Not suitable for production (single-process, non-persistent)
    """

    def __init__(self, max_size: int = REVOCATION_CACHE_MAX_SIZE):
        """
        Initialize in-memory backend.

        Args:
            max_size: Maximum number of entries before LRU eviction
        """
        self._cache: OrderedDict[str, float] = OrderedDict()
        self._sessions: Dict[str, Set[str]] = {}  # session_id -> set of jtis
        self._lock = Lock()
        self._max_size = max_size

        logger.info(
            f"SEC-081: In-memory revocation backend initialized | "
            f"max_size={max_size}"
        )

    def add(self, jti: str, expires_at: int, session_id: Optional[str] = None) -> bool:
        """
        Add token to revocation list.

        Args:
            jti: Token ID to revoke
            expires_at: Token expiration timestamp (for TTL)
            session_id: Optional session ID for session revocation

        Returns:
            True if added successfully
        """
        with self._lock:
            # LRU eviction if at capacity
            while len(self._cache) >= self._max_size:
                self._cache.popitem(last=False)

            # Add with expiration timestamp
            ttl_until = expires_at + REVOCATION_TTL_PADDING_SECONDS
            self._cache[jti] = ttl_until

            # Track session association
            if session_id:
                if session_id not in self._sessions:
                    self._sessions[session_id] = set()
                self._sessions[session_id].add(jti)

            # Move to end (most recently used)
            self._cache.move_to_end(jti)

            return True

    def check(self, jti: str) -> bool:
        """
        Check if token is revoked.

        Args:
            jti: Token ID to check

        Returns:
            True if token is revoked, False otherwise
        """
        with self._lock:
            if jti not in self._cache:
                return False

            # Check if entry has expired (cleanup opportunity)
            expires = self._cache[jti]
            if time.time() > expires:
                del self._cache[jti]
                return False

            return True

    def revoke_session(self, session_id: str) -> int:
        """
        Revoke all tokens for a session.

        Args:
            session_id: Session ID to revoke

        Returns:
            Number of tokens revoked
        """
        with self._lock:
            if session_id not in self._sessions:
                return 0

            jtis = self._sessions.pop(session_id)
            count = len(jtis)

            # Mark all session tokens as revoked with long TTL
            far_future = int(time.time()) + (30 * 24 * 60 * 60)  # 30 days
            for jti in jtis:
                if jti in self._cache:
                    self._cache[jti] = far_future

            return count

    def cleanup(self) -> int:
        """
        Remove expired entries.

        Returns:
            Number of entries removed
        """
        with self._lock:
            now = time.time()
            expired = [k for k, v in self._cache.items() if v < now]
            for k in expired:
                del self._cache[k]
            return len(expired)

    def clear(self) -> None:
        """Clear all entries."""
        with self._lock:
            self._cache.clear()
            self._sessions.clear()

    def stats(self) -> dict:
        """Get backend statistics."""
        with self._lock:
            return {
                "type": "in_memory",
                "entries": len(self._cache),
                "sessions": len(self._sessions),
                "max_size": self._max_size,
            }


class RedisRevocationBackend:
    """
    Redis-based token revocation backend for production.

    Features:
    - Distributed across multiple instances
    - Automatic TTL-based expiration
    - Session revocation support
    - Connection pooling

    Requires: redis package
    """

    def __init__(
        self,
        redis_url: Optional[str] = None,
        redis_client: Optional["redis.Redis"] = None,
    ):
        """
        Initialize Redis backend.

        Args:
            redis_url: Redis connection URL
            redis_client: Existing Redis client (for testing)

        Raises:
            RevocationServiceError: If Redis not available
        """
        if not REDIS_AVAILABLE:
            raise RevocationServiceError(
                "Redis not available. Install with: pip install redis"
            )

        if redis_client:
            self._redis = redis_client
        else:
            url = redis_url or os.environ.get("REDIS_URL", "redis://localhost:6379")
            self._redis = redis.from_url(
                url,
                decode_responses=True,
                socket_timeout=5,
                socket_connect_timeout=5,
            )

        self._prefix = REVOCATION_KEY_PREFIX

        # Test connection
        try:
            self._redis.ping()
            logger.info(f"SEC-081: Redis revocation backend connected")
        except redis.ConnectionError as e:
            logger.error(f"SEC-081: Redis connection failed: {e}")
            raise RevocationServiceError(f"Redis connection failed: {e}")

    def add(self, jti: str, expires_at: int, session_id: Optional[str] = None) -> bool:
        """
        Add token to revocation list.

        Uses Redis SET with TTL for automatic cleanup.

        Args:
            jti: Token ID to revoke
            expires_at: Token expiration timestamp
            session_id: Optional session ID

        Returns:
            True if added successfully
        """
        try:
            # Calculate TTL (token expiry + padding)
            ttl = max(1, expires_at - int(time.time()) + REVOCATION_TTL_PADDING_SECONDS)

            # Store revocation entry
            key = f"{self._prefix}{jti}"
            self._redis.setex(key, ttl, session_id or "revoked")

            # Track session association
            if session_id:
                session_key = f"{self._prefix}session:{session_id}"
                self._redis.sadd(session_key, jti)
                # Session set expires after longest token TTL
                self._redis.expire(session_key, ttl)

            return True

        except redis.RedisError as e:
            logger.error(f"SEC-081: Redis add failed: {e}")
            return False

    def check(self, jti: str) -> bool:
        """
        Check if token is revoked.

        Args:
            jti: Token ID to check

        Returns:
            True if token is revoked
        """
        try:
            key = f"{self._prefix}{jti}"
            return self._redis.exists(key) > 0

        except redis.RedisError as e:
            logger.error(f"SEC-081: Redis check failed: {e}")
            # Fail open (allow) on Redis errors to prevent lockout
            # Log as security event for monitoring
            return False

    def revoke_session(self, session_id: str) -> int:
        """
        Revoke all tokens for a session.

        Args:
            session_id: Session ID to revoke

        Returns:
            Number of tokens revoked
        """
        try:
            session_key = f"{self._prefix}session:{session_id}"

            # Get all JTIs in session
            jtis = self._redis.smembers(session_key)
            if not jtis:
                return 0

            # Extend TTL on all session tokens (30 days)
            pipe = self._redis.pipeline()
            ttl = 30 * 24 * 60 * 60  # 30 days

            for jti in jtis:
                key = f"{self._prefix}{jti}"
                pipe.setex(key, ttl, "session_revoked")

            pipe.delete(session_key)
            pipe.execute()

            return len(jtis)

        except redis.RedisError as e:
            logger.error(f"SEC-081: Redis session revocation failed: {e}")
            return 0

    def clear(self) -> None:
        """Clear all revocation entries (use with caution)."""
        try:
            # Find all keys with prefix
            keys = self._redis.keys(f"{self._prefix}*")
            if keys:
                self._redis.delete(*keys)
        except redis.RedisError as e:
            logger.error(f"SEC-081: Redis clear failed: {e}")

    def stats(self) -> dict:
        """Get backend statistics."""
        try:
            keys = self._redis.keys(f"{self._prefix}*")
            session_keys = [k for k in keys if ":session:" in k]
            return {
                "type": "redis",
                "entries": len(keys) - len(session_keys),
                "sessions": len(session_keys),
                "connected": True,
            }
        except redis.RedisError:
            return {"type": "redis", "connected": False}


class RevocationService:
    """
    Token Revocation Service with configurable backend.

    Provides a unified interface for token revocation with
    automatic backend selection based on environment.

    Attributes:
        backend: Revocation backend (Redis or in-memory)
    """

    def __init__(
        self,
        redis_url: Optional[str] = None,
        use_memory: bool = False,
        backend: Optional[object] = None,
    ):
        """
        Initialize RevocationService.

        Backend selection:
        1. Provided backend (for testing)
        2. In-memory if use_memory=True
        3. Redis if REDIS_URL configured
        4. In-memory fallback

        Args:
            redis_url: Redis connection URL
            use_memory: Force in-memory backend
            backend: Custom backend (for testing)
        """
        self.backend = backend

        if self.backend is None:
            if use_memory:
                self.backend = InMemoryRevocationBackend()
            else:
                # Try Redis first
                url = redis_url or os.environ.get("REDIS_URL")
                if url and REDIS_AVAILABLE:
                    try:
                        self.backend = RedisRevocationBackend(redis_url=url)
                    except RevocationServiceError:
                        logger.warning(
                            "SEC-081: Redis unavailable, falling back to in-memory"
                        )
                        self.backend = InMemoryRevocationBackend()
                else:
                    self.backend = InMemoryRevocationBackend()

        logger.info(
            f"SEC-081: RevocationService initialized | "
            f"backend={self.backend.stats().get('type', 'unknown')}"
        )

    def revoke(self, jti: str, expires_at: int, session_id: Optional[str] = None) -> bool:
        """
        Revoke a token by JTI.

        Args:
            jti: Token ID to revoke
            expires_at: Token expiration timestamp (for TTL calculation)
            session_id: Optional session ID for session tracking

        Returns:
            True if revoked successfully
        """
        success = self.backend.add(jti, expires_at, session_id)

        if success:
            logger.info(
                f"SEC-081: Token revoked | jti={jti} | "
                f"session_id={session_id or 'none'}"
            )
        else:
            logger.warning(f"SEC-081: Failed to revoke token | jti={jti}")

        return success

    def is_revoked(self, jti: str) -> bool:
        """
        Check if a token is revoked.

        Args:
            jti: Token ID to check

        Returns:
            True if token is revoked, False otherwise
        """
        return self.backend.check(jti)

    def revoke_session(self, session_id: str) -> int:
        """
        Revoke all tokens for a session.

        Use for:
        - User logout
        - Password change
        - Security events

        Args:
            session_id: Session ID to revoke

        Returns:
            Number of tokens revoked
        """
        count = self.backend.revoke_session(session_id)

        logger.info(
            f"SEC-081: Session revoked | session_id={session_id} | "
            f"tokens_revoked={count}"
        )

        return count

    def clear(self) -> None:
        """Clear all revocation entries (admin only)."""
        self.backend.clear()
        logger.warning("SEC-081: All revocation entries cleared")

    def stats(self) -> dict:
        """
        Get service statistics.

        Returns:
            Dictionary with backend stats
        """
        return self.backend.stats()


# Singleton instance for dependency injection
_revocation_service_instance: Optional[RevocationService] = None


def get_revocation_service() -> RevocationService:
    """
    Get singleton RevocationService instance.

    Returns:
        RevocationService instance
    """
    global _revocation_service_instance
    if _revocation_service_instance is None:
        _revocation_service_instance = RevocationService()
    return _revocation_service_instance
