# SEC-081: Unified Token Service (RS256 Only)
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# This service replaces 9 existing JWT implementations with a single,
# secure RS256-only token service per SEC-081 requirements.
#
# Compliance: SOC 2 CC6.1, NIST SP 800-131A, PCI-DSS 3.5
"""
Unified Token Service for SEC-081.

This service provides:
- RS256-only JWT creation (no symmetric algorithms)
- Full claims validation with UUID org_id
- TenantContext creation for Layer 1 establishment
- Token revocation checking via RevocationService
- Algorithm confusion attack prevention

Usage:
    from services.token_service import TokenService

    # Initialize
    token_service = TokenService()

    # Create access token
    token = token_service.create_access_token(
        user_id=UUID("..."),
        org_id=UUID("..."),
        role="admin",
        permissions=["read", "write"]
    )

    # Verify and get TenantContext
    context = token_service.verify(token)
"""

import os
import jwt
import secrets
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any
from uuid import UUID, uuid4
from functools import lru_cache

from .unified_auth.constants import (
    ISSUER,
    AUDIENCES,
    ALGORITHM,
    BLOCKED_ALGORITHMS,
    ACCESS_TOKEN_EXPIRE_MINUTES,
    REFRESH_TOKEN_EXPIRE_DAYS,
    REQUIRED_CLAIMS,
    LEGACY_HS256_GRACE_PERIOD_SECONDS,
)
from .unified_auth.exceptions import (
    AuthenticationError,
    TokenExpiredError,
    TokenRevokedError,
    InvalidAlgorithmError,
    InvalidSignatureError,
    InvalidClaimsError,
    KeyNotFoundError,
)
from .unified_auth.tenant_context import TenantContext

logger = logging.getLogger(__name__)


class TokenService:
    """
    Unified RS256 Token Service for SEC-081.

    This service enforces RS256-only signing and provides comprehensive
    token validation with TenantContext creation for Layer 1 establishment.

    Attributes:
        private_key: RSA private key for signing (PEM format)
        public_key: RSA public key for verification (PEM format)
        issuer: Token issuer claim
        audiences: Valid token audiences
        revocation_service: Optional RevocationService for blacklist checking
    """

    def __init__(
        self,
        private_key: Optional[str] = None,
        public_key: Optional[str] = None,
        revocation_service: Optional[Any] = None,
    ):
        """
        Initialize TokenService with RSA keys.

        Keys are loaded from:
        1. Constructor parameters (for testing)
        2. AWS Secrets Manager (production)
        3. Environment variables (fallback)

        Args:
            private_key: RSA private key in PEM format
            public_key: RSA public key in PEM format
            revocation_service: Optional RevocationService instance

        Raises:
            KeyNotFoundError: If keys cannot be loaded in production
        """
        self.issuer = ISSUER
        self.audiences = AUDIENCES
        self.revocation_service = revocation_service

        # Load keys
        self._private_key = private_key or self._load_private_key()
        self._public_key = public_key or self._load_public_key()

        # Key ID for rotation support
        self._key_id = self._generate_key_id()

        logger.info(
            f"SEC-081: TokenService initialized | "
            f"algorithm={ALGORITHM} | "
            f"issuer={self.issuer} | "
            f"key_id={self._key_id}"
        )

    def _load_private_key(self) -> Optional[str]:
        """Load RSA private key from AWS Secrets Manager or environment."""
        # Try AWS Secrets Manager first
        key = self._get_from_secrets_manager("jwt-private-key")
        if key:
            return key

        # Fallback to environment variable
        key = os.environ.get("JWT_PRIVATE_KEY")
        if key:
            # Handle escaped newlines
            return key.replace("\\n", "\n")

        # Production requires keys
        environment = os.environ.get("ENVIRONMENT", "development")
        if environment.lower() == "production":
            raise KeyNotFoundError(
                "SEC-081 CRITICAL: JWT private key not configured in production",
                key_type="private"
            )

        # Development: Generate ephemeral key (warning logged)
        logger.warning(
            "SEC-081: Generating ephemeral RSA key for development. "
            "DO NOT use in production!"
        )
        return self._generate_development_keys()[0]

    def _load_public_key(self) -> str:
        """Load RSA public key from AWS Secrets Manager or environment."""
        # Try AWS Secrets Manager first
        key = self._get_from_secrets_manager("jwt-public-key")
        if key:
            return key

        # Fallback to environment variable
        key = os.environ.get("JWT_PUBLIC_KEY")
        if key:
            return key.replace("\\n", "\n")

        # Production requires keys
        environment = os.environ.get("ENVIRONMENT", "development")
        if environment.lower() == "production":
            raise KeyNotFoundError(
                "SEC-081 CRITICAL: JWT public key not configured in production",
                key_type="public"
            )

        # Development: Use generated key
        return self._generate_development_keys()[1]

    @lru_cache(maxsize=1)
    def _generate_development_keys(self) -> tuple:
        """Generate ephemeral RSA keys for development only."""
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
        from cryptography.hazmat.backends import default_backend

        # Generate RSA-2048 key pair
        private_key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend()
        )

        # Serialize private key
        private_pem = private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()
        ).decode("utf-8")

        # Serialize public key
        public_pem = private_key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo
        ).decode("utf-8")

        return (private_pem, public_pem)

    def _get_from_secrets_manager(self, key_name: str) -> Optional[str]:
        """Get secret from AWS Secrets Manager."""
        try:
            import boto3
            from botocore.exceptions import ClientError

            client = boto3.client(
                "secretsmanager",
                region_name=os.environ.get("AWS_REGION", "us-east-2")
            )

            secret_id = f"owkai-pilot/sec079/{key_name.upper().replace('-', '_')}"
            response = client.get_secret_value(SecretId=secret_id)
            return response.get("SecretString")

        except Exception as e:
            logger.debug(f"SEC-081: Could not load {key_name} from Secrets Manager: {e}")
            return None

    def _generate_key_id(self) -> str:
        """Generate key ID from public key fingerprint."""
        import hashlib
        if self._public_key:
            fingerprint = hashlib.sha256(self._public_key.encode()).hexdigest()[:8]
            return f"ascend-{fingerprint}"
        return f"ascend-{secrets.token_hex(4)}"

    # =========================================================================
    # TOKEN CREATION
    # =========================================================================

    def create_access_token(
        self,
        user_id: UUID,
        org_id: UUID,
        role: str = "user",
        permissions: Optional[List[str]] = None,
        tenant_id: Optional[str] = None,
        session_id: Optional[str] = None,
        additional_claims: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Create RS256-signed access token.

        Args:
            user_id: User UUID (becomes 'sub' claim)
            org_id: Organization UUID (Layer 1 tenant context)
            role: User role (admin, user, viewer)
            permissions: List of permission strings
            tenant_id: Human-readable tenant identifier
            session_id: Session identifier for revocation
            additional_claims: Extra claims to include

        Returns:
            JWT access token string

        Raises:
            KeyNotFoundError: If private key not available
        """
        if not self._private_key:
            raise KeyNotFoundError("Private key not available for signing")

        now = datetime.utcnow()
        jti = f"tok_{secrets.token_urlsafe(16)}"
        session = session_id or f"sess_{secrets.token_urlsafe(12)}"

        # Build claims with UUID org_id (per SEC-081 Modification 1)
        claims = {
            # Standard claims
            "iss": self.issuer,
            "aud": self.audiences,
            "sub": str(user_id),
            "iat": int(now.timestamp()),
            "exp": int((now + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)).timestamp()),
            "jti": jti,
            # Ascend custom claims
            "type": "access",
            "org_id": str(org_id),  # UUID as string
            "tenant_id": tenant_id or str(org_id),
            "role": role,
            "permissions": permissions or [],
            "session_id": session,
        }

        # Merge additional claims
        if additional_claims:
            claims.update(additional_claims)

        # Add header with key ID for rotation support
        headers = {
            "kid": self._key_id,
            "alg": ALGORITHM,
            "typ": "JWT",
        }

        # Sign with RS256
        token = jwt.encode(
            claims,
            self._private_key,
            algorithm=ALGORITHM,
            headers=headers
        )

        logger.info(
            f"SEC-081: Access token created | "
            f"jti={jti} | "
            f"user_id={user_id} | "
            f"org_id={org_id} | "
            f"role={role}"
        )

        return token

    def create_refresh_token(
        self,
        user_id: UUID,
        org_id: UUID,
        session_id: Optional[str] = None,
    ) -> str:
        """
        Create RS256-signed refresh token.

        Refresh tokens have minimal claims and longer expiration.

        Args:
            user_id: User UUID
            org_id: Organization UUID
            session_id: Session identifier for revocation

        Returns:
            JWT refresh token string
        """
        if not self._private_key:
            raise KeyNotFoundError("Private key not available for signing")

        now = datetime.utcnow()
        jti = f"rtok_{secrets.token_urlsafe(16)}"
        session = session_id or f"sess_{secrets.token_urlsafe(12)}"

        claims = {
            "iss": self.issuer,
            "aud": self.audiences,
            "sub": str(user_id),
            "iat": int(now.timestamp()),
            "exp": int((now + timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)).timestamp()),
            "jti": jti,
            "type": "refresh",
            "org_id": str(org_id),
            "session_id": session,
        }

        headers = {
            "kid": self._key_id,
            "alg": ALGORITHM,
            "typ": "JWT",
        }

        token = jwt.encode(
            claims,
            self._private_key,
            algorithm=ALGORITHM,
            headers=headers
        )

        logger.info(
            f"SEC-081: Refresh token created | "
            f"jti={jti} | "
            f"user_id={user_id} | "
            f"org_id={org_id}"
        )

        return token

    # =========================================================================
    # TOKEN VERIFICATION
    # =========================================================================

    def verify(
        self,
        token: str,
        expected_type: str = "access",
        client_ip: Optional[str] = None,
    ) -> TenantContext:
        """
        Verify JWT token and return TenantContext.

        This is the primary verification method that:
        1. Validates algorithm is RS256 (blocks HS256, none)
        2. Verifies cryptographic signature
        3. Validates all required claims
        4. Checks token revocation status
        5. Creates immutable TenantContext

        Args:
            token: JWT token string
            expected_type: Expected token type ("access" or "refresh")
            client_ip: Client IP for context (optional)

        Returns:
            Immutable TenantContext for Layer 1 establishment

        Raises:
            InvalidAlgorithmError: If algorithm is blocked
            InvalidSignatureError: If signature verification fails
            InvalidClaimsError: If required claims missing/invalid
            TokenExpiredError: If token has expired
            TokenRevokedError: If token has been revoked
        """
        # Step 1: Inspect header WITHOUT verification to check algorithm
        self._validate_algorithm(token)

        # Step 2: Decode and verify signature
        try:
            claims = jwt.decode(
                token,
                self._public_key,
                algorithms=[ALGORITHM],  # ONLY RS256
                issuer=self.issuer,
                audience=self.audiences,
                leeway=30,  # Allow 30s clock skew
                options={
                    "verify_signature": True,
                    "verify_exp": True,
                    "verify_nbf": False,  # nbf not included in token
                    "verify_iat": False,  # iat is informational, not security-critical
                    "verify_iss": True,
                    "verify_aud": True,
                    "require": ["exp", "iat", "sub", "jti", "org_id"],
                }
            )
        except jwt.ExpiredSignatureError as e:
            jti = self._extract_jti_unsafe(token)
            logger.warning(f"SEC-081: Token expired | jti={jti}")
            raise TokenExpiredError("Token has expired", jti=jti)
        except jwt.InvalidSignatureError:
            logger.warning("SEC-081: Invalid token signature")
            raise InvalidSignatureError("Token signature verification failed")
        except jwt.InvalidAlgorithmError as e:
            logger.warning(f"SEC-081: Invalid algorithm in token: {e}")
            raise InvalidAlgorithmError(str(e))
        except jwt.InvalidAudienceError:
            logger.warning("SEC-081: Invalid token audience")
            raise InvalidClaimsError("Invalid audience claim", invalid_claims=["aud"])
        except jwt.InvalidIssuerError:
            logger.warning("SEC-081: Invalid token issuer")
            raise InvalidClaimsError("Invalid issuer claim", invalid_claims=["iss"])
        except jwt.PyJWTError as e:
            logger.warning(f"SEC-081: JWT verification failed: {e}")
            raise AuthenticationError(f"Token verification failed: {e}")

        # Step 3: Validate token type
        token_type = claims.get("type")
        if token_type != expected_type:
            logger.warning(
                f"SEC-081: Token type mismatch | "
                f"expected={expected_type} | "
                f"actual={token_type}"
            )
            raise InvalidClaimsError(
                f"Expected {expected_type} token, got {token_type}",
                invalid_claims=["type"]
            )

        # Step 4: Check revocation status
        jti = claims["jti"]
        if self.revocation_service and self.revocation_service.is_revoked(jti):
            logger.warning(f"SEC-081: Token revoked | jti={jti}")
            raise TokenRevokedError("Token has been revoked", jti=jti)

        # Step 5: Create immutable TenantContext
        context = TenantContext.from_claims(
            claims,
            auth_method="jwt",
            client_ip=client_ip
        )

        logger.debug(
            f"SEC-081: Token verified | "
            f"jti={jti} | "
            f"user_id={claims['sub']} | "
            f"org_id={claims['org_id']}"
        )

        return context

    def _validate_algorithm(self, token: str) -> None:
        """
        Validate token algorithm BEFORE signature verification.

        This prevents algorithm confusion attacks (CVE-2015-9235) where
        an attacker signs with HS256 using the public key as the secret.

        Args:
            token: JWT token string

        Raises:
            InvalidAlgorithmError: If algorithm is blocked
        """
        try:
            # Decode header only (no verification)
            header = jwt.get_unverified_header(token)
            alg = header.get("alg", "")

            # Check for blocked algorithms
            if alg in BLOCKED_ALGORITHMS:
                logger.warning(
                    f"SEC-081: BLOCKED ALGORITHM DETECTED | "
                    f"algorithm={alg} | "
                    f"This may be an attack attempt!"
                )
                raise InvalidAlgorithmError(
                    f"Algorithm '{alg}' is blocked. Only RS256 is allowed.",
                    algorithm=alg
                )

            # Enforce RS256 only
            if alg != ALGORITHM:
                logger.warning(
                    f"SEC-081: Non-RS256 algorithm detected | "
                    f"algorithm={alg}"
                )
                raise InvalidAlgorithmError(
                    f"Only RS256 algorithm is allowed. Got: {alg}",
                    algorithm=alg
                )

        except jwt.exceptions.DecodeError:
            raise AuthenticationError("Invalid token format")

    def _extract_jti_unsafe(self, token: str) -> Optional[str]:
        """Extract JTI from token without verification (for logging only)."""
        try:
            payload = jwt.decode(token, options={"verify_signature": False})
            return payload.get("jti")
        except Exception:
            return None

    # =========================================================================
    # TOKEN REVOCATION
    # =========================================================================

    def revoke(self, token: str) -> bool:
        """
        Revoke a token by adding its JTI to the blacklist.

        Args:
            token: JWT token to revoke

        Returns:
            True if revoked successfully, False otherwise
        """
        if not self.revocation_service:
            logger.warning("SEC-081: Revocation service not configured")
            return False

        try:
            # Extract claims without full verification (token may be expired)
            claims = jwt.decode(token, options={"verify_signature": False})
            jti = claims.get("jti")
            exp = claims.get("exp")

            if jti and exp:
                self.revocation_service.revoke(jti, exp)
                logger.info(f"SEC-081: Token revoked | jti={jti}")
                return True

        except Exception as e:
            logger.error(f"SEC-081: Failed to revoke token: {e}")

        return False

    def revoke_session(self, session_id: str) -> int:
        """
        Revoke all tokens for a session.

        Args:
            session_id: Session identifier

        Returns:
            Number of tokens revoked
        """
        if not self.revocation_service:
            logger.warning("SEC-081: Revocation service not configured")
            return 0

        count = self.revocation_service.revoke_session(session_id)
        logger.info(f"SEC-081: Session revoked | session_id={session_id} | count={count}")
        return count

    # =========================================================================
    # UTILITY METHODS
    # =========================================================================

    def decode_unsafe(self, token: str) -> dict:
        """
        Decode token without verification (for debugging only).

        WARNING: Never use this for authorization decisions!

        Args:
            token: JWT token string

        Returns:
            Token claims dictionary
        """
        return jwt.decode(token, options={"verify_signature": False})

    def get_token_info(self, token: str) -> dict:
        """
        Get token information for debugging/logging.

        Args:
            token: JWT token string

        Returns:
            Token info dictionary (safe for logging)
        """
        try:
            header = jwt.get_unverified_header(token)
            claims = jwt.decode(token, options={"verify_signature": False})

            return {
                "algorithm": header.get("alg"),
                "key_id": header.get("kid"),
                "type": claims.get("type"),
                "jti": claims.get("jti"),
                "org_id": claims.get("org_id"),
                "issued_at": datetime.fromtimestamp(claims.get("iat", 0)).isoformat(),
                "expires_at": datetime.fromtimestamp(claims.get("exp", 0)).isoformat(),
                "is_expired": datetime.utcnow().timestamp() > claims.get("exp", 0),
            }
        except Exception as e:
            return {"error": str(e)}


# Singleton instance for dependency injection
_token_service_instance: Optional[TokenService] = None


def get_token_service() -> TokenService:
    """
    Get singleton TokenService instance.

    Returns:
        TokenService instance
    """
    global _token_service_instance
    if _token_service_instance is None:
        _token_service_instance = TokenService()
    return _token_service_instance
