"""
RBAC-001: Multi-Pool JWT Validator (Platform + Per-Org Pools)
Generated by Ascend Engineering Team
Application Owner: OW-KAI Technologies, Inc.

Architecture:
  - Platform Pool (1): Ascend internal staff (scope='platform', org_id=null)
  - Tenant Pools (N): One per customer organization (scope='org', org_id=UUID)

Pool Resolution:
  1. Extract issuer (iss) from token
  2. Check if issuer matches platform pool → scope='platform'
  3. Otherwise, lookup organization by cognito_user_pool_id → scope='org'
  4. Fail secure if pool not found

Security Standards: SOC 2 CC6.1, NIST IA-5, PCI-DSS 8.2
"""

import os
import logging
import requests
from dataclasses import dataclass
from typing import Dict, Optional, Tuple
from datetime import datetime
from threading import Lock

from jose import jwt, jwk, JWTError
from jose.backends import RSAKey
from sqlalchemy.orm import Session

logger = logging.getLogger("enterprise.multi_pool_jwt")


# =============================================================================
# CONFIGURATION
# =============================================================================

@dataclass
class PoolConfig:
    """Configuration for a Cognito user pool."""
    pool_id: str
    client_id: str
    region: str
    scope: str  # 'platform' or 'org'
    organization_id: Optional[int] = None  # Set for org pools

    @property
    def issuer(self) -> str:
        """Cognito issuer URL."""
        return f"https://cognito-idp.{self.region}.amazonaws.com/{self.pool_id}"

    @property
    def jwks_url(self) -> str:
        """JWKS endpoint URL."""
        return f"{self.issuer}/.well-known/jwks.json"


def get_platform_pool_config() -> Optional[PoolConfig]:
    """
    Load platform pool configuration from environment variables.

    Returns:
        PoolConfig for platform pool, or None if not configured
    """
    region = os.getenv("COGNITO_REGION", "us-east-2")
    platform_pool_id = os.getenv("COGNITO_PLATFORM_POOL_ID")
    platform_client_id = os.getenv("COGNITO_PLATFORM_CLIENT_ID")

    if platform_pool_id and platform_client_id:
        logger.info(f"Platform pool configured: {platform_pool_id}")
        return PoolConfig(
            pool_id=platform_pool_id,
            client_id=platform_client_id,
            region=region,
            scope="platform",
            organization_id=None
        )

    logger.warning("Platform pool not configured (COGNITO_PLATFORM_POOL_ID missing)")
    return None


def get_fallback_customer_pool_config() -> Optional[PoolConfig]:
    """
    Get fallback customer pool from ENV (backward compatibility).
    Used when org lookup fails or for legacy tokens.
    """
    region = os.getenv("COGNITO_REGION", "us-east-2")
    pool_id = os.getenv("COGNITO_USER_POOL_ID")
    client_id = os.getenv("COGNITO_APP_CLIENT_ID")

    if pool_id and client_id:
        return PoolConfig(
            pool_id=pool_id,
            client_id=client_id,
            region=region,
            scope="org",
            organization_id=None  # Will be set from token claims
        )
    return None


# =============================================================================
# JWKS CACHE (Per-Pool)
# =============================================================================

class JWKSCache:
    """
    Thread-safe JWKS cache with per-pool key storage.

    Features:
    - 60-minute TTL per pool
    - Automatic refresh on cache miss
    - Thread-safe operations
    """

    TTL_SECONDS = 3600  # 60 minutes

    def __init__(self):
        self._cache: Dict[str, Dict[str, RSAKey]] = {}
        self._timestamps: Dict[str, datetime] = {}
        self._lock = Lock()

    def get_keys(self, pool: PoolConfig) -> Dict[str, RSAKey]:
        """
        Get JWKS keys for a pool, fetching if needed.

        Args:
            pool: Pool configuration

        Returns:
            Dict mapping key ID (kid) to RSAKey
        """
        with self._lock:
            pool_id = pool.pool_id
            now = datetime.utcnow()

            # Check if cached and not expired
            if pool_id in self._cache:
                cached_at = self._timestamps.get(pool_id)
                if cached_at and (now - cached_at).total_seconds() < self.TTL_SECONDS:
                    return self._cache[pool_id]

            # Fetch fresh keys
            keys = self._fetch_keys(pool)
            self._cache[pool_id] = keys
            self._timestamps[pool_id] = now

            return keys

    def _fetch_keys(self, pool: PoolConfig) -> Dict[str, RSAKey]:
        """Fetch JWKS keys from Cognito endpoint."""
        try:
            logger.info(f"Fetching JWKS from {pool.jwks_url}")
            response = requests.get(pool.jwks_url, timeout=10)
            response.raise_for_status()

            keys_data = response.json()["keys"]
            keys = {}

            for key_data in keys_data:
                kid = key_data["kid"]
                keys[kid] = jwk.construct(key_data)

            logger.info(f"Fetched {len(keys)} keys for pool {pool.pool_id}")
            return keys

        except Exception as e:
            logger.error(f"Failed to fetch JWKS for pool {pool.pool_id}: {e}")
            raise

    def refresh(self, pool: PoolConfig) -> Dict[str, RSAKey]:
        """Force refresh keys for a pool."""
        with self._lock:
            if pool.pool_id in self._cache:
                del self._cache[pool.pool_id]
            if pool.pool_id in self._timestamps:
                del self._timestamps[pool.pool_id]

        return self.get_keys(pool)

    def clear(self):
        """Clear all cached keys."""
        with self._lock:
            self._cache.clear()
            self._timestamps.clear()


# =============================================================================
# ORGANIZATION POOL LOOKUP
# =============================================================================

class OrgPoolResolver:
    """
    Resolves organization pools from database.

    Caches org pool configs to avoid repeated DB queries.
    """

    CACHE_TTL_SECONDS = 300  # 5 minutes

    def __init__(self):
        self._cache: Dict[str, Tuple[PoolConfig, datetime]] = {}  # issuer -> (config, timestamp)
        self._lock = Lock()

    def resolve_by_issuer(self, issuer: str, db: Session) -> Optional[PoolConfig]:
        """
        Resolve organization pool config from issuer URL.

        Args:
            issuer: Cognito issuer URL (e.g., https://cognito-idp.us-east-2.amazonaws.com/us-east-2_xxx)
            db: Database session

        Returns:
            PoolConfig if found, None otherwise
        """
        # Check cache first
        with self._lock:
            if issuer in self._cache:
                config, cached_at = self._cache[issuer]
                if (datetime.utcnow() - cached_at).total_seconds() < self.CACHE_TTL_SECONDS:
                    return config

        # Extract pool ID from issuer URL
        # Format: https://cognito-idp.{region}.amazonaws.com/{pool_id}
        try:
            pool_id = issuer.split("/")[-1]
            region = issuer.split(".")[1].replace("cognito-idp.", "")
        except (IndexError, AttributeError):
            logger.error(f"Invalid issuer format: {issuer}")
            return None

        # Query database for organization with this pool
        try:
            from models import Organization

            org = db.query(Organization).filter(
                Organization.cognito_user_pool_id == pool_id,
                Organization.cognito_pool_status == "active"
            ).first()

            if not org:
                logger.warning(f"No active organization found for pool {pool_id}")
                return None

            config = PoolConfig(
                pool_id=pool_id,
                client_id=org.cognito_app_client_id,
                region=org.cognito_region or region,
                scope="org",
                organization_id=org.id
            )

            # Cache the result
            with self._lock:
                self._cache[issuer] = (config, datetime.utcnow())

            logger.info(f"Resolved pool {pool_id} to org {org.id} ({org.name})")
            return config

        except Exception as e:
            logger.error(f"Failed to resolve org pool: {e}")
            return None

    def clear_cache(self):
        """Clear the org pool cache."""
        with self._lock:
            self._cache.clear()


# =============================================================================
# MULTI-POOL JWT VALIDATOR
# =============================================================================

class MultiPoolJWTValidator:
    """
    Validates JWTs from Platform and Per-Organization Cognito pools.

    Validation Flow:
    1. Extract issuer (iss) from unverified token
    2. Check if issuer matches platform pool → scope='platform'
    3. Otherwise, lookup organization by pool ID → scope='org'
    4. Fetch JWKS keys for that pool (cached)
    5. Verify RS256 signature
    6. Validate all claims (iss, aud, exp, token_use)
    7. Return validated payload with scope and org_id
    """

    def __init__(self):
        self.platform_pool = get_platform_pool_config()
        self.fallback_pool = get_fallback_customer_pool_config()
        self.jwks_cache = JWKSCache()
        self.org_resolver = OrgPoolResolver()

        logger.info(f"MultiPoolJWTValidator initialized")
        logger.info(f"  Platform pool: {self.platform_pool.pool_id if self.platform_pool else 'NOT CONFIGURED'}")
        logger.info(f"  Fallback pool: {self.fallback_pool.pool_id if self.fallback_pool else 'NOT CONFIGURED'}")

    def _extract_issuer(self, token: str) -> Optional[str]:
        """Extract issuer from token without verification."""
        try:
            claims = jwt.get_unverified_claims(token)
            return claims.get("iss")
        except JWTError:
            return None

    def identify_pool(self, token: str, db: Session) -> Optional[PoolConfig]:
        """
        Identify which pool issued a token.

        Priority:
        1. Platform pool (if issuer matches)
        2. Per-org pool (lookup by issuer in database)
        3. Fallback pool (backward compatibility)

        Args:
            token: JWT token string
            db: Database session for org lookup

        Returns:
            PoolConfig if pool identified, None otherwise
        """
        issuer = self._extract_issuer(token)
        if not issuer:
            logger.warning("Token missing 'iss' claim")
            return None

        # Check platform pool first
        if self.platform_pool and issuer == self.platform_pool.issuer:
            logger.debug(f"Token from platform pool")
            return self.platform_pool

        # Try to resolve from database
        org_pool = self.org_resolver.resolve_by_issuer(issuer, db)
        if org_pool:
            logger.debug(f"Token from org pool: org_id={org_pool.organization_id}")
            return org_pool

        # Fallback pool (backward compatibility)
        if self.fallback_pool and issuer == self.fallback_pool.issuer:
            logger.debug(f"Token from fallback pool")
            return self.fallback_pool

        logger.warning(f"Unknown issuer: {issuer}")
        return None

    def validate(self, token: str, db: Session) -> dict:
        """
        Validate a JWT token from any pool.

        Args:
            token: JWT token string
            db: Database session for org lookup

        Returns:
            Validated payload with added fields:
            - scope: 'platform' or 'org'
            - pool_source: Pool ID that issued the token
            - org_id: Organization ID (for org tokens)

        Raises:
            JWTError: If validation fails
        """
        # Step 1: Identify pool
        pool = self.identify_pool(token, db)
        if not pool:
            raise JWTError("Token issued by unknown pool - fail secure")

        # Step 2: Get unverified header for key ID
        header = jwt.get_unverified_header(token)
        kid = header.get("kid")

        if not kid:
            raise JWTError("Token missing 'kid' in header")

        # Step 3: Get public key from cache
        keys = self.jwks_cache.get_keys(pool)

        if kid not in keys:
            logger.info(f"Key {kid} not in cache, refreshing JWKS for {pool.pool_id}")
            keys = self.jwks_cache.refresh(pool)

            if kid not in keys:
                raise JWTError(f"Unknown key ID: {kid}")

        public_key = keys[kid]

        # Step 4: Verify signature and decode
        try:
            payload = jwt.decode(
                token,
                public_key,
                algorithms=["RS256"],
                audience=pool.client_id,
                issuer=pool.issuer,
                options={
                    "verify_aud": True,
                    "verify_iss": True,
                    "verify_exp": True,
                    "require_exp": True,
                }
            )
        except JWTError as e:
            logger.error(f"JWT verification failed for pool {pool.pool_id}: {e}")
            raise

        # Step 5: Validate token_use
        token_use = payload.get("token_use")
        if token_use not in ("id", "access"):
            raise JWTError(f"Invalid token_use: {token_use}")

        # Step 6: Enrich payload with scope info
        payload["scope"] = pool.scope
        payload["pool_source"] = pool.pool_id

        # Set org_id from pool config (for org pools resolved from DB)
        if pool.scope == "org" and pool.organization_id:
            payload["org_id"] = pool.organization_id
        elif pool.scope == "platform":
            payload["org_id"] = None

        logger.debug(f"Token validated: scope={pool.scope}, pool={pool.pool_id}, org_id={payload.get('org_id')}")

        return payload


# =============================================================================
# MODULE-LEVEL INSTANCE
# =============================================================================

_validator: Optional[MultiPoolJWTValidator] = None
_validator_lock = Lock()


def get_validator() -> MultiPoolJWTValidator:
    """Get or create the singleton validator instance."""
    global _validator

    if _validator is None:
        with _validator_lock:
            if _validator is None:
                _validator = MultiPoolJWTValidator()

    return _validator


def validate_token(token: str, db: Session, allow_fallback: bool = True) -> dict:
    """
    Convenience function to validate a token.

    Args:
        token: JWT token string
        db: Database session for org lookup
        allow_fallback: If True, attempt fallback validation on unknown issuer

    Returns:
        Validated payload with scope, pool_source, and org_id
    """
    validator = get_validator()
    return validator.validate(token, db)
