"""initial schema

Revision ID: d67b2f1fd8c6
Revises: 
Create Date: 2025-08-18 14:59:19.182833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67b2f1fd8c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=True),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_method', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_subject_email'), ['subject_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_subject_id'), ['subject_id'], unique=False)

    op.create_table('data_erasure_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('erasure_type', sa.String(length=50), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('records_affected', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_method', sa.String(length=50), nullable=False),
    sa.Column('legal_basis', sa.String(length=100), nullable=False),
    sa.Column('retention_exception', sa.Boolean(), nullable=False),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('verification_hash', sa.String(length=64), nullable=False),
    sa.Column('backup_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_erasure_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_erasure_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_erasure_logs_subject_email'), ['subject_email'], unique=False)

    op.create_table('data_lineage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=True),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=20), nullable=False),
    sa.Column('legal_basis_processing', sa.String(length=100), nullable=False),
    sa.Column('retention_period', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_deletion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_requests', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_lineage_subject_email'), ['subject_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_lineage_subject_id'), ['subject_id'], unique=False)

    op.create_table('data_subject_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('legal_basis', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_details', sa.JSON(), nullable=False),
    sa.Column('identity_verification', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('compliance_framework', sa.String(length=20), nullable=False),
    sa.Column('retention_period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_subject_requests_subject_email'), ['subject_email'], unique=False)

    op.create_table('mcp_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('policy_description', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=20), nullable=True),
    sa.Column('server_patterns', sa.JSON(), nullable=True),
    sa.Column('namespace_patterns', sa.JSON(), nullable=True),
    sa.Column('verb_patterns', sa.JSON(), nullable=True),
    sa.Column('resource_patterns', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('risk_threshold', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('required_approval_level', sa.Integer(), nullable=True),
    sa.Column('auto_approve_conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('compliance_framework', sa.String(length=50), nullable=True),
    sa.Column('regulatory_reference', sa.String(length=200), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_server_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mcp_server_id', sa.String(length=100), nullable=False),
    sa.Column('mcp_server_name', sa.String(length=200), nullable=False),
    sa.Column('mcp_server_version', sa.String(length=50), nullable=True),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('verb', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('payload_size', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_level', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=100), nullable=True),
    sa.Column('policy_result', sa.String(length=50), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('approver_id', sa.String(length=100), nullable=True),
    sa.Column('approver_email', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('execution_result', sa.String(length=50), nullable=True),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('data_classification', sa.String(length=50), nullable=True),
    sa.Column('compliance_tags', sa.JSON(), nullable=True),
    sa.Column('audit_trail_id', sa.UUID(), nullable=True),
    sa.Column('evidence_pack_id', sa.UUID(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('geo_location', sa.String(length=100), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('bytes_transferred', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('mcp_server_actions', schema=None) as batch_op:
        batch_op.create_index('idx_mcp_approval', ['status', 'requires_approval'], unique=False)
        batch_op.create_index('idx_mcp_compliance', ['compliance_tags'], unique=False)
        batch_op.create_index('idx_mcp_risk_level', ['risk_level', 'status'], unique=False)
        batch_op.create_index('idx_mcp_server_namespace', ['mcp_server_id', 'namespace'], unique=False)
        batch_op.create_index('idx_mcp_session', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('idx_mcp_user_time', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_audit_trail_id'), ['audit_trail_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_mcp_server_id'), ['mcp_server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_namespace'), ['namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_actions_verb'), ['verb'], unique=False)

    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('server_name', sa.String(length=200), nullable=False),
    sa.Column('server_description', sa.Text(), nullable=True),
    sa.Column('server_version', sa.String(length=50), nullable=True),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('supported_namespaces', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('auth_method', sa.String(length=50), nullable=True),
    sa.Column('trust_level', sa.String(length=20), nullable=True),
    sa.Column('default_risk_level', sa.String(length=20), nullable=True),
    sa.Column('requires_approval_by_default', sa.Boolean(), nullable=True),
    sa.Column('max_approval_level', sa.Integer(), nullable=True),
    sa.Column('total_actions', sa.Integer(), nullable=True),
    sa.Column('failed_actions', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_table('smart_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smart_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_rules_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smart_rules_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('approval_level', sa.Integer(), nullable=True),
    sa.Column('is_emergency_approver', sa.Boolean(), nullable=True),
    sa.Column('max_risk_approval', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
    sa.Column('workflow_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nist_control', sa.String(), nullable=True),
    sa.Column('nist_description', sa.Text(), nullable=True),
    sa.Column('mitre_tactic', sa.String(), nullable=True),
    sa.Column('mitre_technique', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('target_system', sa.String(), nullable=True),
    sa.Column('target_resource', sa.String(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('approval_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_id'), ['id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('pending_action_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_title'), ['title'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('compliance_impact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('integration_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('endpoint_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('authentication', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_failure', sa.DateTime(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_endpoints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_endpoints_name'), ['name'], unique=False)

    op.create_table('log_audit_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('compliance_framework', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_audit_trails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_audit_trails_id'), ['id'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_id'), ['id'], unique=False)

    op.create_table('mcp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('authenticated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('total_actions', sa.Integer(), nullable=True),
    sa.Column('successful_actions', sa.Integer(), nullable=True),
    sa.Column('failed_actions', sa.Integer(), nullable=True),
    sa.Column('bytes_transferred', sa.Integer(), nullable=True),
    sa.Column('auth_token_hash', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.server_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_sessions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_mcp_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('pending_agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('target_system', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('action_payload', sa.Text(), nullable=True),
    sa.Column('authorization_status', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('ai_risk_score', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_result', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('contextual_risk_factors', sa.Text(), nullable=True),
    sa.Column('required_approval_level', sa.Integer(), nullable=True),
    sa.Column('current_approval_level', sa.Integer(), nullable=True),
    sa.Column('workflow_stage', sa.String(), nullable=True),
    sa.Column('auto_approve_at', sa.DateTime(), nullable=True),
    sa.Column('approval_chain', sa.Text(), nullable=True),
    sa.Column('required_approvers', sa.Text(), nullable=True),
    sa.Column('pending_approvers', sa.Text(), nullable=True),
    sa.Column('primary_approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('conditional_approval', sa.Boolean(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('approval_duration', sa.Integer(), nullable=True),
    sa.Column('approval_scope', sa.Text(), nullable=True),
    sa.Column('compliance_frameworks', sa.Text(), nullable=True),
    sa.Column('audit_trail', sa.Text(), nullable=True),
    sa.Column('emergency_approver_id', sa.Integer(), nullable=True),
    sa.Column('break_glass_used', sa.Boolean(), nullable=True),
    sa.Column('execution_duration', sa.Float(), nullable=True),
    sa.Column('affected_resources', sa.Text(), nullable=True),
    sa.Column('approval_level_required', sa.Integer(), nullable=True),
    sa.Column('escalation_timer', sa.DateTime(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('nist_control', sa.String(), nullable=True),
    sa.Column('mitre_tactic', sa.String(), nullable=True),
    sa.Column('mitre_technique', sa.String(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('denied_by', sa.Integer(), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('emergency_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_by', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['denied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_agent_actions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_agent_actions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_agent_actions_request_id'), ['request_id'], unique=True)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('nist_controls', sa.JSON(), nullable=True),
    sa.Column('mitre_tactics', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_id'), ['id'], unique=False)

    op.create_table('system_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('config_type', sa.String(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configurations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configurations_key'), ['key'], unique=True)

    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('executed_by', sa.String(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('execution_details', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_id'), ['id'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('step_type', sa.String(), nullable=True),
    sa.Column('timeout_hours', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_id'), ['id'], unique=False)

    op.create_table('rule_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('false_positive', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('suggested_changes', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_feedbacks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_feedbacks_id'))

    op.drop_table('rule_feedbacks')
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('system_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configurations_key'))
        batch_op.drop_index(batch_op.f('ix_system_configurations_id'))

    op.drop_table('system_configurations')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_id'))

    op.drop_table('rules')
    with op.batch_alter_table('pending_agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_agent_actions_request_id'))
        batch_op.drop_index(batch_op.f('ix_pending_agent_actions_id'))
        batch_op.drop_index(batch_op.f('ix_pending_agent_actions_agent_id'))

    op.drop_table('pending_agent_actions')
    with op.batch_alter_table('mcp_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_sessions_client_id'))

    op.drop_table('mcp_sessions')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_id'))

    op.drop_table('logs')
    with op.batch_alter_table('log_audit_trails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_audit_trails_id'))

    op.drop_table('log_audit_trails')
    with op.batch_alter_table('integration_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_endpoints_name'))
        batch_op.drop_index(batch_op.f('ix_integration_endpoints_id'))

    op.drop_table('integration_endpoints')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_title'))
        batch_op.drop_index(batch_op.f('ix_alerts_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_agent_id'))

    op.drop_table('agent_actions')
    op.drop_table('workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('smart_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_rules_id'))
        batch_op.drop_index(batch_op.f('ix_smart_rules_agent_id'))

    op.drop_table('smart_rules')
    op.drop_table('mcp_servers')
    with op.batch_alter_table('mcp_server_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_verb'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_session_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_namespace'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_mcp_server_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_client_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_audit_trail_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_actions_approver_id'))
        batch_op.drop_index('idx_mcp_user_time')
        batch_op.drop_index('idx_mcp_session')
        batch_op.drop_index('idx_mcp_server_namespace')
        batch_op.drop_index('idx_mcp_risk_level')
        batch_op.drop_index('idx_mcp_compliance')
        batch_op.drop_index('idx_mcp_approval')

    op.drop_table('mcp_server_actions')
    op.drop_table('mcp_policies')
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_subject_email'))

    op.drop_table('data_subject_requests')
    with op.batch_alter_table('data_lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_lineage_subject_id'))
        batch_op.drop_index(batch_op.f('ix_data_lineage_subject_email'))

    op.drop_table('data_lineage')
    with op.batch_alter_table('data_erasure_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_erasure_logs_subject_email'))
        batch_op.drop_index(batch_op.f('ix_data_erasure_logs_request_id'))

    op.drop_table('data_erasure_logs')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_subject_id'))
        batch_op.drop_index(batch_op.f('ix_consent_records_subject_email'))

    op.drop_table('consent_records')
    # ### end Alembic commands ###
