# RBAC Task 5: Enterprise Permission Service
# SEC-088: Two-Tier Permission System
# Generated by Ascend Engineering Team
# Application Owner: OW-KAI Technologies, Inc.
#
# This service integrates with:
# - MultiPoolJWTValidator (scope determination)
# - EnterpriseRBAC (existing permission system)
# - Audit logging (SOC 2 compliance)
#
# Compliance: SOC 2 CC6.1, NIST AC-3, NIST AC-6, PCI-DSS 7.1
"""
Enterprise Permission Service for Two-Tier Identity.

This service provides permission checking for both platform (Ascend staff)
and tenant (customer) users, integrating with the existing RBAC system
while adding scope-based isolation.

Architecture:
    Platform Tier (Ascend Staff)
    ├── Super Admin: Full platform access
    ├── Support: Read-only platform + org metadata
    └── Billing: Billing operations only

    Tenant Tier (Customer Users)
    ├── Owner: Full organization access + billing
    ├── Admin: Full org access except billing
    ├── Approver: View + approve workflows
    ├── Operator: Create/manage resources
    └── Viewer: Read-only access

Usage:
    from services.permission_service import PermissionService

    permission_service = PermissionService(db)

    # Check permission
    allowed = await permission_service.has_permission(
        user=token_claims,
        resource="policies",
        action="create"
    )

    # Use decorator
    @require_permission("policies", "create")
    async def create_policy(...):
        ...
"""

import logging
from typing import Dict, List, Optional, Set, Any
from datetime import datetime
from functools import wraps
from enum import Enum

from fastapi import HTTPException, status

# Import existing RBAC system for tenant users
from rbac_manager import enterprise_rbac, Permission, AccessLevel

logger = logging.getLogger(__name__)


# =============================================================================
# PLATFORM ROLES & PERMISSIONS
# =============================================================================

class PlatformRole(str, Enum):
    """Platform tier roles for Ascend staff."""
    SUPER_ADMIN = "Super Admin"
    SUPPORT = "Support"
    BILLING = "Billing"


# Platform permission matrix (what Ascend staff can do)
PLATFORM_PERMISSIONS: Dict[str, Dict[str, List[str]]] = {
    PlatformRole.SUPER_ADMIN: {
        # Organization management (metadata only)
        "orgs": ["list", "read", "suspend", "activate", "create"],
        # Billing management
        "billing": ["read", "write", "refund"],
        # Platform health/monitoring
        "health": ["read"],
        "usage": ["read"],
        # User management (cross-org for platform users only)
        "platform_users": ["list", "read", "create", "update", "delete"],
        # System administration
        "system": ["config", "backup", "maintenance"],
    },
    PlatformRole.SUPPORT: {
        "orgs": ["list", "read"],
        "billing": ["read"],
        "health": ["read"],
        "usage": ["read"],
        "platform_users": ["list", "read"],
        "system": [],
    },
    PlatformRole.BILLING: {
        "orgs": ["list"],
        "billing": ["read", "write", "refund"],
        "health": [],
        "usage": [],
        "platform_users": [],
        "system": [],
    },
}


# =============================================================================
# TENANT ROLES & PERMISSIONS
# =============================================================================

class TenantRole(str, Enum):
    """Tenant tier roles for customer users."""
    OWNER = "Owner"
    ADMIN = "Admin"
    APPROVER = "Approver"
    OPERATOR = "Operator"
    VIEWER = "Viewer"


# Tenant permission matrix (what customers can do within their org)
TENANT_PERMISSIONS: Dict[str, Dict[str, List[str]]] = {
    TenantRole.OWNER: {
        "policies": ["read", "create", "update", "delete"],
        "agents": ["read", "create", "update", "delete", "register", "suspend"],
        "workflows": ["read", "create", "update", "delete", "approve", "reject"],
        "alerts": ["read", "create", "update", "delete", "acknowledge", "dismiss"],
        "rules": ["read", "create", "update", "delete"],
        "users": ["read", "create", "update", "delete", "invite", "suspend"],
        "org_settings": ["read", "update"],
        "billing": ["read", "update"],
        "api_keys": ["read", "create", "revoke"],
        "audit": ["read", "export"],
        "integrations": ["read", "create", "update", "delete"],
    },
    TenantRole.ADMIN: {
        "policies": ["read", "create", "update", "delete"],
        "agents": ["read", "create", "update", "delete", "register", "suspend"],
        "workflows": ["read", "create", "update", "delete", "approve", "reject"],
        "alerts": ["read", "create", "update", "delete", "acknowledge", "dismiss"],
        "rules": ["read", "create", "update", "delete"],
        "users": ["read", "create", "update", "delete", "invite"],
        "org_settings": ["read"],
        "billing": [],  # Admin cannot access billing
        "api_keys": ["read", "create", "revoke"],
        "audit": ["read", "export"],
        "integrations": ["read", "create", "update", "delete"],
    },
    TenantRole.APPROVER: {
        "policies": ["read"],
        "agents": ["read"],
        "workflows": ["read", "approve", "reject"],
        "alerts": ["read", "acknowledge"],
        "rules": ["read"],
        "users": [],
        "org_settings": [],
        "billing": [],
        "api_keys": [],
        "audit": ["read"],
        "integrations": ["read"],
    },
    TenantRole.OPERATOR: {
        "policies": ["read", "create", "update"],
        "agents": ["read", "create", "update", "register"],
        "workflows": ["read", "create"],
        "alerts": ["read", "create", "acknowledge"],
        "rules": ["read", "create", "update"],
        "users": [],
        "org_settings": [],
        "billing": [],
        "api_keys": ["read"],
        "audit": ["read"],
        "integrations": ["read", "create", "update"],
    },
    TenantRole.VIEWER: {
        "policies": ["read"],
        "agents": ["read"],
        "workflows": ["read"],
        "alerts": ["read"],
        "rules": ["read"],
        "users": [],
        "org_settings": [],
        "billing": [],
        "api_keys": [],
        "audit": ["read"],
        "integrations": ["read"],
    },
}


# =============================================================================
# PERMISSION SERVICE
# =============================================================================

class PermissionService:
    """
    Enterprise Permission Service for Two-Tier Identity.

    Provides permission checking with:
    - Scope-based access (platform vs org)
    - Role-based permissions within scope
    - Audit logging for all decisions
    - Fail-secure behavior
    """

    def __init__(self, db_session=None):
        """
        Initialize permission service.

        Args:
            db_session: SQLAlchemy session for audit logging
        """
        self._db = db_session
        self._legacy_rbac = enterprise_rbac

        logger.info("SEC-088: PermissionService initialized")

    async def has_permission(
        self,
        user: Any,  # TokenClaims or dict
        resource: str,
        action: str,
        resource_id: Optional[str] = None,
        context: Optional[Dict] = None,
    ) -> bool:
        """
        Check if user has permission for action on resource.

        FAIL SECURE: Any error results in denial.

        Args:
            user: TokenClaims or dict with user info
            resource: Resource type (policies, agents, etc.)
            action: Action (read, create, update, delete, etc.)
            resource_id: Specific resource ID (optional)
            context: Additional context for decision (optional)

        Returns:
            True if allowed, False if denied
        """
        try:
            # Extract user info
            user_id = self._get_user_id(user)
            scope = self._get_scope(user)
            org_id = self._get_org_id(user)
            roles = self._get_roles(user)

            # Check permission based on scope
            if scope == "platform":
                allowed = self._check_platform_permission(roles, resource, action)
            else:
                allowed = self._check_tenant_permission(roles, resource, action)

            # Log the decision
            await self._log_permission_check(
                user_id=user_id,
                org_id=org_id,
                scope=scope,
                roles=roles,
                resource=resource,
                action=action,
                resource_id=resource_id,
                decision="allowed" if allowed else "denied",
                reason=f"Role check: {'pass' if allowed else 'fail'}",
            )

            return allowed

        except Exception as e:
            # FAIL SECURE
            logger.error(f"SEC-088: Permission check error | error={e}")
            await self._log_permission_check(
                user_id=self._get_user_id(user) if user else "unknown",
                org_id=self._get_org_id(user) if user else None,
                scope=self._get_scope(user) if user else "unknown",
                roles=[],
                resource=resource,
                action=action,
                resource_id=resource_id,
                decision="denied",
                reason=f"Error: {str(e)}",
            )
            return False

    def has_permission_sync(
        self,
        user: Any,
        resource: str,
        action: str,
        resource_id: Optional[str] = None,
    ) -> bool:
        """
        Synchronous version of has_permission.

        For use in non-async contexts.
        """
        import asyncio
        try:
            loop = asyncio.get_event_loop()
            return loop.run_until_complete(
                self.has_permission(user, resource, action, resource_id)
            )
        except RuntimeError:
            # No event loop, create one
            return asyncio.run(
                self.has_permission(user, resource, action, resource_id)
            )

    def _check_platform_permission(
        self,
        roles: List[str],
        resource: str,
        action: str,
    ) -> bool:
        """Check permission for platform users."""
        for role in roles:
            try:
                platform_role = PlatformRole(role)
                permissions = PLATFORM_PERMISSIONS.get(platform_role, {})
                allowed_actions = permissions.get(resource, [])
                if action in allowed_actions:
                    return True
            except ValueError:
                # Not a valid platform role, skip
                continue

        return False

    def _check_tenant_permission(
        self,
        roles: List[str],
        resource: str,
        action: str,
    ) -> bool:
        """Check permission for tenant users."""
        for role in roles:
            try:
                tenant_role = TenantRole(role)
                permissions = TENANT_PERMISSIONS.get(tenant_role, {})
                allowed_actions = permissions.get(resource, [])
                if action in allowed_actions:
                    return True
            except ValueError:
                # Not a valid tenant role, try legacy RBAC
                continue

        # Fallback to legacy RBAC system for backward compatibility
        return self._check_legacy_permission(roles, resource, action)

    def _check_legacy_permission(
        self,
        roles: List[str],
        resource: str,
        action: str,
    ) -> bool:
        """
        Check permission using legacy RBAC system.

        Maps resource:action to legacy Permission constants.
        """
        # Map new resource:action to legacy permissions
        legacy_map = {
            ("policies", "read"): Permission.RULES_VIEW,
            ("policies", "create"): Permission.RULES_CREATE,
            ("policies", "update"): Permission.RULES_MODIFY,
            ("policies", "delete"): Permission.RULES_DELETE,
            ("alerts", "read"): Permission.ALERTS_VIEW,
            ("alerts", "acknowledge"): Permission.ALERTS_ACKNOWLEDGE,
            ("alerts", "dismiss"): Permission.ALERTS_DISMISS,
            ("rules", "read"): Permission.RULES_VIEW,
            ("rules", "create"): Permission.RULES_CREATE,
            ("rules", "update"): Permission.RULES_MODIFY,
            ("rules", "delete"): Permission.RULES_DELETE,
            ("users", "read"): Permission.USERS_VIEW,
            ("users", "create"): Permission.USERS_CREATE,
            ("users", "update"): Permission.USERS_MODIFY,
            ("users", "delete"): Permission.USERS_DELETE,
            ("audit", "read"): Permission.AUDIT_VIEW,
            ("audit", "export"): Permission.AUDIT_EXPORT,
        }

        legacy_permission = legacy_map.get((resource, action))
        if not legacy_permission:
            return False

        # Try each role as an access level
        for role in roles:
            try:
                # Map role name to access level
                level_map = {
                    "admin": AccessLevel.ADMIN,
                    "manager": AccessLevel.MANAGER,
                    "user": AccessLevel.BASIC,
                    "power_user": AccessLevel.POWER,
                    "executive": AccessLevel.EXECUTIVE,
                }
                access_level = level_map.get(role.lower(), AccessLevel.BASIC)
                if self._legacy_rbac.has_permission(access_level, legacy_permission):
                    return True
            except Exception:
                continue

        return False

    # =========================================================================
    # USER INFO EXTRACTION
    # =========================================================================

    def _get_user_id(self, user: Any) -> str:
        """Extract user ID from TokenClaims or dict."""
        if hasattr(user, "user_id"):
            return user.user_id
        elif hasattr(user, "sub"):
            return user.sub
        elif isinstance(user, dict):
            return user.get("user_id") or user.get("sub") or "unknown"
        return "unknown"

    def _get_scope(self, user: Any) -> str:
        """Extract scope from TokenClaims or dict."""
        if hasattr(user, "scope"):
            return user.scope
        elif isinstance(user, dict):
            return user.get("scope", "org")
        return "org"

    def _get_org_id(self, user: Any) -> Optional[str]:
        """Extract org_id from TokenClaims or dict."""
        if hasattr(user, "org_id"):
            return user.org_id
        elif isinstance(user, dict):
            return user.get("org_id") or user.get("organization_id")
        return None

    def _get_roles(self, user: Any) -> List[str]:
        """Extract roles from TokenClaims or dict."""
        roles = []

        # Check cognito_groups
        if hasattr(user, "cognito_groups"):
            roles.extend(user.cognito_groups)
        elif isinstance(user, dict):
            groups = user.get("cognito_groups", [])
            if groups:
                roles.extend(groups)

        # Check role field
        if hasattr(user, "role") and user.role:
            roles.append(user.role)
        elif isinstance(user, dict) and user.get("role"):
            roles.append(user.get("role"))

        # Default to Viewer if no roles
        if not roles:
            roles = ["Viewer"]

        return roles

    # =========================================================================
    # AUDIT LOGGING
    # =========================================================================

    async def _log_permission_check(
        self,
        user_id: str,
        org_id: Optional[str],
        scope: str,
        roles: List[str],
        resource: str,
        action: str,
        resource_id: Optional[str],
        decision: str,
        reason: str,
    ) -> None:
        """Log permission check for audit trail."""
        logger.info(
            f"SEC-088: PERMISSION_CHECK | "
            f"user_id={user_id} | "
            f"org_id={org_id} | "
            f"scope={scope} | "
            f"roles={roles} | "
            f"resource={resource} | "
            f"action={action} | "
            f"resource_id={resource_id} | "
            f"decision={decision} | "
            f"reason={reason}"
        )

        # TODO: Write to audit_logs table for persistence
        # This would be implemented with the AuditLog model

    # =========================================================================
    # UTILITY METHODS
    # =========================================================================

    def get_user_permissions(self, user: Any) -> Dict[str, List[str]]:
        """
        Get all permissions for a user.

        Returns dict of resource -> actions.
        """
        scope = self._get_scope(user)
        roles = self._get_roles(user)

        permissions: Dict[str, Set[str]] = {}

        if scope == "platform":
            for role in roles:
                try:
                    platform_role = PlatformRole(role)
                    role_perms = PLATFORM_PERMISSIONS.get(platform_role, {})
                    for resource, actions in role_perms.items():
                        if resource not in permissions:
                            permissions[resource] = set()
                        permissions[resource].update(actions)
                except ValueError:
                    continue
        else:
            for role in roles:
                try:
                    tenant_role = TenantRole(role)
                    role_perms = TENANT_PERMISSIONS.get(tenant_role, {})
                    for resource, actions in role_perms.items():
                        if resource not in permissions:
                            permissions[resource] = set()
                        permissions[resource].update(actions)
                except ValueError:
                    continue

        # Convert sets to lists
        return {k: list(v) for k, v in permissions.items()}

    def get_role_hierarchy(self, scope: str) -> List[str]:
        """Get role hierarchy for a scope (highest to lowest)."""
        if scope == "platform":
            return [r.value for r in PlatformRole]
        else:
            return [r.value for r in TenantRole]


# =============================================================================
# SINGLETON & DEPENDENCY
# =============================================================================

_permission_service: Optional[PermissionService] = None


def get_permission_service(db_session=None) -> PermissionService:
    """Get singleton PermissionService instance."""
    global _permission_service
    if _permission_service is None:
        _permission_service = PermissionService(db_session)
    return _permission_service


# =============================================================================
# FASTAPI DECORATORS
# =============================================================================

def require_permission(resource: str, action: str):
    """
    Decorator to require specific permission.

    Usage:
        @router.post("/policies")
        @require_permission("policies", "create")
        async def create_policy(
            claims: TokenClaims = Depends(require_org_scope),
            ...
        ):
            ...
    """
    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            # Find TokenClaims or user dict in kwargs
            user = None
            for key, value in kwargs.items():
                if hasattr(value, "scope") or (isinstance(value, dict) and "scope" in value):
                    user = value
                    break

            if not user:
                logger.error(f"SEC-088: No user context in request | resource={resource} | action={action}")
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail="User context not found",
                )

            # Check permission
            service = get_permission_service()
            allowed = await service.has_permission(user, resource, action)

            if not allowed:
                user_id = service._get_user_id(user)
                roles = service._get_roles(user)
                logger.warning(
                    f"SEC-088: Permission denied | "
                    f"user_id={user_id} | "
                    f"resource={resource} | "
                    f"action={action} | "
                    f"roles={roles}"
                )
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN,
                    detail=f"Permission denied: {resource}:{action}",
                )

            return await func(*args, **kwargs)
        return wrapper
    return decorator


def require_any_permission(*permissions: tuple):
    """
    Decorator to require any of multiple permissions.

    Usage:
        @require_any_permission(("policies", "create"), ("policies", "update"))
        async def modify_policy(...):
            ...
    """
    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            user = None
            for key, value in kwargs.items():
                if hasattr(value, "scope") or (isinstance(value, dict) and "scope" in value):
                    user = value
                    break

            if not user:
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail="User context not found",
                )

            service = get_permission_service()
            for resource, action in permissions:
                if await service.has_permission(user, resource, action):
                    return await func(*args, **kwargs)

            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Permission denied: requires one of {permissions}",
            )
        return wrapper
    return decorator
